### ISSUE TITLE
missing context help for completion

### ISSUE THREAD

**Issue by nimo23** [angelozerr/typescript.java#100]
I have installed **Typescript IDE 1.1.0** in Eclipse Neon.SR1.

However, it does not fully work:

- Eclipse-**Preferences->javascript->typescript exists**, **however no menu-item  "Angular2" exists.**
- Content Assist within *.ts-files does not work

What is wrong?

**Comment by nimo23** [comment]
was may fault: have not installed angular2-plugin. Now it works.

**Comment by nimo23** [comment]
I have installed angular2-eclipse plugin (https://github.com/angelozerr/angular2-eclipse), now menu-item ("Angular2") is visible. However, I dont have content assist and help within *.ts-files as expected:

When I type "import {}", no typescript-proposals (content-assist) appear.

When I hover over @Component({, then this unformatted help is shown:

![angular-help](https://cloud.githubusercontent.com/assets/3045549/20037782/654bd2c8-a427-11e6-934c-af79b6576af5.png)

**Comment by angelozerr** [comment]
> When I type "import {}", no typescript-proposals (content-assist) appear:

Which completion do you wish to have? 

> When I hover over @Component({, then this unformatted help is shown:

Yes, I must improve hover, please create an new issue.

> But this is not shown in my editor. What is wrong?

Please share your project which causes problem and tell me what is your problem.

**Comment by nimo23** [comment]
>Which completion do you wish to have? 

The same completion as shown above in as shown in https://github.com/angelozerr/typescript.java.
Actually, I have made completion work. However, it looks like this:


![ang](https://cloud.githubusercontent.com/assets/3045549/20039173/f2e0601e-a43f-11e6-8c29-48c9ea304b18.png)

instead of that picture above (shown in https://github.com/angelozerr/typescript.java)

**Comment by angelozerr** [comment]
> instead of that picture above (shown in https://github.com/angelozerr/typescript.java)

Yes it's normal. This picture is old. In your case completion ignore upper/lower case and use fuzzy algorythm to filter completion items like VSCode does and JDT.

**Comment by nimo23** [comment]
>Yes it's normal. This picture is old.

But the "old" picture shows context help on the right side. Actually only "import Component" is shown instead of full api description.

**Comment by angelozerr** [comment]
> Please provide full API-Description while showing the context-help.

Ok your problem is about context help for completion. I will study your problem.

**Comment by nimo23** [comment]
Yes, thank you. Sorry for the misleading topic name. 

I have changed it to "missing context help for completion"

**Comment by angelozerr** [comment]
@nimo23 I have tested and it works for me:

![typescriptcompletion](https://cloud.githubusercontent.com/assets/1932211/20042555/6452fd7e-a47c-11e6-8ed3-e814dd2c8872.png)

Could you share your project please. Thanks.

**Comment by nimo23** [comment]
Strange. In my editor this is not shown.

[angular-quickstart.zip](https://github.com/angelozerr/typescript.java/files/574875/angular-quickstart.zip)

**Comment by angelozerr** [comment]
It's because your angular2 version was not the same than me. They have changed the comments. It seems that TypeScript tsserver cannot retrieve the well documentation with your version of angular2.

To see the problem, I suggest you that you enable tsserver trace and you will see that "import Component" is returned by tssererver response.

I suggest you that you create an issue at https://github.com/Microsoft/TypeScript/issues by explaining very well the problem, give the TypeScritp version that you are using, gives the request/response tsserver, angular2 version and comment of Component.

**Comment by nimo23** [comment]
You are right. It is not a TS IDE-Isuee:

I tried it also with VSCode. The same behaviour here. No API-Description.

**Comment by Springrbua** [comment]
@nimo23 @angelozerr I guess this one can be closed, right?

**Comment by angelozerr** [comment]
I keep opened this issue because I need to improve completion context info to support markdown syntax like I have done for hover.

**Comment by angelozerr** [comment]
Completion context info now uses TextMate. here the result:

![image](https://user-images.githubusercontent.com/1932211/27551247-e6a3c38a-5aa2-11e7-8e54-f1343658c82b.png)
