### ISSUE TITLE
wrong node version in tsconfig-editor

### ISSUE THREAD

**Issue by nimo23** [angelozerr/typescript.java#101]
tsconfig-editor shows this under Category "Compiler"
"Consume TypeScript 2.0.6 with nodejs v4.2.4". 

However, I use my installed version of node.js which is actually **node version 7.0.0**

![ang](https://cloud.githubusercontent.com/assets/3045549/20037876/72c954f0-a429-11e6-8f5f-317c25808d31.png)

**Comment by angelozerr** [comment]
I will study the problem. Thanks for reporting this issue.

**Comment by angelozerr** [comment]
That's strange it works for me (I'm  on Windows). I must improve this properties page to check that path is a valid node.js and display version of node.js.

Have you some logs in the Problem/Logs View? I cannot test with your Linux OS.

**Comment by nimo23** [comment]
I am using Mac OS. I deleted my eclipse-log-file, restarted eclipse and looked at the new generated error-log file. I have searched for typescript errors and it occurs:

```
!MESSAGE Error while getting TypeScript occurrences.
!STACK 0
ts.TypeScriptNoContentAvailableException: No content available.
```

The full stacktrace below:


[log.txt](https://github.com/angelozerr/typescript.java/files/574129/log.txt)

**Comment by angelozerr** [comment]
This error log comes from when you select a content in the editor which is not a TypeScript element (ex: space). This error must never loggued. I have fixed that with https://github.com/angelozerr/typescript.java/commit/7eb34c86c816d020909ef1126442e97047a87431

Could you just check with a terminal, that 

`/usr/local/bin/node --version`

returns 7.0.0?

I'm executing this command to know the version of node.js

**Comment by angelozerr** [comment]
You had configured node path with Global Preferences where there were a bug. I have fixed it.
