### ISSUE TITLE
provide New File-Wizard/Template for .ts

### ISSUE THREAD

**Issue by nimo23** [angelozerr/typescript.java#106]
Actually I have to go to "File->New->File" to create a ".ts"-file. 
Would be nice to have a "File->New->TS-File"-Wizard.

Maybe this "file-wizard" could be extended to be filled with a already provided template coming from TS-IDE (TS-IDE also provides templates for ng-bootstrap, ng-component or react-templates).

**Comment by angelozerr** [comment]
Glad you create this issue:) I have not implemented that because I don't know if it's really interesting? For Angular2 we have Angular CLI support (ng init) which initialize the project, but for other?

I would liek to avoid passing a lot of time to develop a wizard which generates a tsconfig.json and ts file basic. So please give me more information about your idea (which wizards do you wish, which files must be generated, etc....)

**Comment by nimo23** [comment]
I am in doubt with my suggestion. I use the terminal a lot and I guess TS-IDE with autocompletion is enough. But maybe only provide "File->New->Typescript-File". However, it is not really needed. Because we can do it with "File->New->File" to create a ".ts"-file.

So I guess, if you think the same, I can close this issue.

**Comment by angelozerr** [comment]
> So I guess, if you think the same, I can close this issue.

Exactly, but if other people want to have this feature, I could implement it but I prefer developping other features that I have planned  like TextMate syntax coloration, quick fix support, compilation with tsserver etc.

**Comment by nimo23** [comment]
> but I prefer developping other features that I have planned

Yes, that sounds great. I guess, there is really no need for gui like wizard.

**Comment by angelozerr** [comment]
> Yes, that sounds great.

Glad you like those ideas:

 * for TextMate see https://github.com/angelozerr/textmate.java/ and I start to have cool renderer like:

![](https://cloud.githubusercontent.com/assets/1932211/20024121/dbd0f6a6-a2e4-11e6-8bf5-552ef964928b.png) 

but I have a lot of bugs -(

 * for quick fix, see https://github.com/angelozerr/typescript.java/issues/97
 * for tsserver compilation see https://github.com/angelozerr/typescript.java/issues/109
