### ISSUE TITLE
hide typescript compiled resources as default

### ISSUE THREAD

**Issue by nimo23** [angelozerr/typescript.java#107]
**Why dont you make the following setting not as default by TS IDE:**

![1](https://cloud.githubusercontent.com/assets/3045549/20071400/aac548cc-a524-11e6-8993-7feb14a1429f.png)

**js-files will be shown by tree expanding, so you can make the above setting as the default.**

![1](https://cloud.githubusercontent.com/assets/3045549/20071439/d3e093c4-a524-11e6-8263-1f9a435f8e47.png)

**Comment by nimo23** [comment]
Okay, I guess, the actual default is the right choice, because user can set "outDir" in tsconfig ot another directory and sees the compiled files there, so no need to hide it as default.

**Comment by angelozerr** [comment]
@nimo23 it's a good observation. I have not setted this option by default, because I was afraid that user didn't understand why js, map files are not visible (user must expand the ts file to see it).

But any feedback are welcome, if you think it'sa good idea to enable it by default.

**Comment by nimo23** [comment]
>because I was afraid that user didn't understand why js, map files are not visible

I was thinking that typescript-project should hide js-files by default because developer thinks in typescript not in javascript. However, as user can set outDir to another directory, I guess, it does not matter to set it not as default. But this is the first I did, I set it as default.
