### ISSUE TITLE
Add auto import and auto complete hint support

### ISSUE THREAD

**Issue by georgema1982** [angelozerr/typescript.java#108]
It would be better if auto import and auto complete hint is supported in salsa editor like the Java editor does. Right now when I type a class and hit ctrl+space, no hint is provided. I hope that, like Java editor, a list of available types are listed and when one is selected, it's also added to the import statements.

**Comment by angelozerr** [comment]
Same issue than https://github.com/angelozerr/typescript.java/issues/22
