### ISSUE TITLE
outputDir not always work

### ISSUE THREAD

**Issue by nimo23** [angelozerr/typescript.java#111]
I have "outDir": "app/js" in tsconfig.json

```
{
	"compilerOptions": {
		"target": "es5",
		"module": "commonjs",
		"moduleResolution": "node",
		"sourceMap": true,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"removeComments": false,
		"noImplicitAny": false,
		"outDir": "app/js"
	},
	"compileOnSave": true,
	"buildOnSave": false,
	"exclude": [
		"node_modules"
	]
}
```

The folder app/js does exist. And compiling works, the origin ts-files are stored in folder "app" compiled files are generated in "app/js".

However, when I change outDir to "outDir": "app/build", then TS Server will generate these files again in "app/js" instead of "app/build". I created a new folder "build" in "app" and tried again. TS Server creates these files in "app/js" instead of "app/build".

**Comment by angelozerr** [comment]
Please install 1.2.0-SNAPSHOT. I have fixed a problem with tsconfig.json cache. Tell me if it fixes your issue. Thanks!

**Comment by angelozerr** [comment]
None answer, I close this issue.

**Comment by nimo23** [comment]
Hello,

sorry,  I was on vacation and forgot to reply. I am actually very busy. I have just checked it now and it seems, that this issue is gone. I cannot reproduce it.

Thanks.
