### ISSUE TITLE
enable Automatic Type Acquisition (ATA)

### ISSUE THREAD

**Issue by nimo23** [angelozerr/typescript.java#116]
VS Code 1.7.2 has enabled Automatic Type Acquisition (ATA) feature by default (https://code.visualstudio.com/updates). Would be nice to introduce ATA as a option in Typescript Eclipse-Projects as well.

**Comment by angelozerr** [comment]
Yes sure! Could you give me some idea (UI, etc) how it could work?

**Comment by nimo23** [comment]
Include a option in "Eclipse->Settings->JavaScript->Typescript" to enable/disable ATA.

If enabled, then "typescript.java" can provide IntelliSense for pure js-files by obtaining the coresponding declaration files of the js-files within the project-root with the help of TS Server and npmjs service. So user does not need to manually include TypeScript declaration files.

**Comment by nimo23** [comment]
Maybe another option would be to have a context menu within the project explorer, such as "refresh ATA". With this, Eclipse User can **manually trigger** IntelliSense for js-files. So TS IDE does not include or ping npmjs service by itself. However, when enabled in settings, TS IDE can also include declaration files as soon as a js-file is included within the ts-project-folder.

For example, user include jquery.js within project root without typescript declaration file, then user can trigger "refresh ATA" with caches/includes declaration files of jquery to provide intellisense in ts-files. I am not sure about that, but I TS Server has also the ability to provide intellisense for js-files even when no official declaration file of this js-file exists. But I am not sure.

**Comment by nimo23** [comment]
More information here: https://code.visualstudio.com/updates#_better-javascript-intellisense

**Comment by angelozerr** [comment]
@nimo23 could you explain how ATA works with VSCode? I have tried to declare jquery in a package.json 

```json
{
    "dependencies": {
        "jquery": "3.1.1",
    }
}
```

and open a ts file, type jQuery and I though it that VSCode will download jQuery but it seems that it doesn't work like this. Thanks for your help.

**Comment by nimo23** [comment]
Is "typescript.disableAutomaticTypeAcquisition" set to "false"?

**Comment by angelozerr** [comment]
Here my settings.json

```
{
    "typescript.tsdk": "./node_modules/typescript/lib",
    "typescript.tsserver.trace": "messages",
    "typescript.disableAutomaticTypeAcquisition": false
}
```

I'm using VSCode 1.7.2 with TypeScript 2.1.4.

**Comment by nimo23** [comment]
As said in https://code.visualstudio.com/updates#_better-javascript-intellisense it should work. However, I tested it with a new project and it also does not work. Maybe not ready yet.

**Comment by nimo23** [comment]
In my editor it works before because I had def files within my old project. However, in new projects, it does not realy work.

**Comment by angelozerr** [comment]
When the download is done? When you open completion?

Anyway it seems (according the VSCode code) that ATA is not very complex to implement it since it is managed with tsserver (very cool!). Once I will understand how ATA works with VSCode, I will try to implement it.

**Comment by nimo23** [comment]
>When the download is done?

good question. I think, yes, then it should fetch def file. I dont know about performance while opening code completion and fetching resource, IDE source editing could hang..not very user friendly.

**Comment by angelozerr** [comment]
> good question.

I will study it.

>  I dont know about performance while opening code completion and fetching resource, IDE source editing could hang..not very user friendly.

Eclipse Oxygen should provide an async completion feature. I must test that.

**Comment by angelozerr** [comment]
See https://discventionstech.wordpress.com/2016/12/06/vs-code-automatic-type-acquisition-gotchas/ I will test that. It seems that it works only with js files and not with ts files. I will try with VSCode. @nimo23 is that, it works only with js files?

**Comment by nimo23** [comment]
ATA works only for js-files, ts files dont need ATA. When referencing js files in ts files then ts server use ATA for js files..

**Comment by angelozerr** [comment]
Ok thanks @nimo23 for your answer. I will try with VSCode and I will try to do the same thing for Eclipse. The cool thing is that the hard task is managed with tsserver, so perhaps the ATA integration could be easy.

**Comment by boniatillo-com** [comment]
Thanks for your comments Angelo. Anyway I will do a release with TS preview, I think many Phaser Editor users will love it.

**Comment by angelozerr** [comment]
@nimo23 I have studied ATA with typescript.java and as it uses tsserver, ATA works like a charm (tested with TypeScript 2.1.5). But today you must follow the following rules:

 * don't use embed node.js, but an installed node.js which provides npm too. I will try to fix this problem by adding npm in the embed node.js.

 * declare in your tsconfig.json: 

```
{
	"typeAcquisition": {
		"enable": true
	}
}
```

And that's all! After that, create a ts file (it works with ts too) like:

`import {} from "jquery";`

Wait few seconds and try to open (Ctrl+Click) the jquery. It should open the ..AppData\Local\Microsoft\TypeScript\node_modules\@types\jquery\index.d.ts file

I must improve the console to display trace of typings when download is done.

**Comment by angelozerr** [comment]
@nimo23 now embed node.js contains the npm https://github.com/angelozerr/typescript.java/issues/136

So you should just declare in your tsconfig.json:

```
{
	"typeAcquisition": {
		"enable": true
	}
}
```

and it should work.

**Comment by angelozerr** [comment]
@nimo23 ATA is now available. See https://github.com/angelozerr/typescript.java/wiki/ATA
