### ISSUE TITLE
opening a ts file in the editor (without textmate coloring) results in an exception

### ISSUE THREAD

**Issue by jcompagner** [angelozerr/typescript.java#119]
ts.TypeScriptException: [tsserver] file cannot be null
	at ts.nodejs.NodejsProcess.checkFile(NodejsProcess.java:57)
	at ts.nodejs.NodejsProcess.<init>(NodejsProcess.java:44)
	at ts.nodejs.NodejsProcessManager.create(NodejsProcessManager.java:85)
	at ts.client.TypeScriptServiceClient.<init>(TypeScriptServiceClient.java:134)
	at ts.resources.TypeScriptProject.createServiceClient(TypeScriptProject.java:240)
	at ts.resources.TypeScriptProject.getClient(TypeScriptProject.java:200)
	at ts.resources.TypeScriptProject.openFile(TypeScriptProject.java:87)
	at ts.resources.AbstractTypeScriptFile.open(AbstractTypeScriptFile.java:90)
	at ts.eclipse.ide.internal.core.resources.IDETypeScriptProject.openFile(IDETypeScriptProject.java:175)
	at ts.eclipse.ide.internal.ui.EditorActivationTracker$2.run(EditorActivationTracker.java:92)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by angelozerr** [comment]
I think it's because your TypeScript Runtime is not good. Select the well TypeScript Runtime in the preferences JavaScript / TypeScript / Runtime.

I must fix this problem in the https://github.com/angelozerr/typescript.java/issues/121

**Comment by jcompagner** [comment]
What ever I try (I use the embedded, it now says 2.1.4) that doesn't help, I can't change to something else really but toggling everything I know doesn't fix it. 

Will try to debug it my self later

**Comment by angelozerr** [comment]
Perhaps your embed TypeScript Runtime preferences is setted in your project properties? To open it, open your tsconfig.json and you will see a link to your TypeScript Runtime (I think it will display "null"). Click on this link and change your Runtime.

**Comment by jcompagner** [comment]
my tsconfig.json only is this:

{
    "compilerOptions": {
        "module": "commonjs",
        "sourceMap": false
    },
    "include": [
        "META-INF/**/*.ts"
    ]   
}

i do use project settings, but those are not stored in the tsconfig file but in the project specific files (in the .settings dir of the project)

and if i open the ts.eclipse.ide.core.prefs file then i see the problem:

embeddedTypeScriptId=TypeScript (2.0.6)

that should be 2.1.4 i guess. But the ui you don't see that... there you really see "TypeScript 2.1.4"
I see it 2 times also for the tslintembedded

but even toggling first to installed type script (and give a path) then back to embedded doesn't store the correct value, only pressing Restore Defaults and then selecting it all again and then it is saved correctly.

So this is something that should be looked at i guess, if there is really only 1 option for that list and that is not the selected value, we should update it automatically or i guess have an empty value in it selected..

**Comment by jcompagner** [comment]
i updated to the latest and now textmate also works, and fixing the project settings made all the other problems also fine. (textmate is only visible the first time you open a file i think, then i guess plugins are loaded in, the second time it is not really visible anymore

1 thing is weird, in 1 project i get a warning on top of the file that the file is not included in the tsconfig files selection (but i don't use that i just use include), but the weird thing is in another project that also only uses include pattern instead of files it doesn't say that..

**Comment by angelozerr** [comment]
> So this is something that should be looked at i guess, if there is really only 1 option for that list and that is not the selected value, we should update it automatically or i guess have an empty value in it selected..

See https://github.com/angelozerr/typescript.java/issues/121

>textmate is only visible the first time you open a file i think, then i guess plugins are loaded in, the second time it is not really visible anymore

You mean that textmate is working? Do you like it? It's not perfect (there is some problem with big big ts file)

> 1 thing is weird, in 1 project i get a warning on top of the file that the file is not included in the tsconfig files selection (but i don't use that i just use include), but the weird thing is in another project that also only uses include pattern instead of files it doesn't say that..

See https://github.com/angelozerr/typescript.java/issues/86

**Comment by angelozerr** [comment]
https://github.com/angelozerr/typescript.java/issues/121 should fix this issue.
