### ISSUE TITLE
Collaboration how to

### ISSUE THREAD

**Issue by boniatillo-com** [angelozerr/typescript.java#123]
Hello @angelozerr 

I want to collaborate with this project, is there any guide to setup a dev environment? What neon version etc...

**Comment by angelozerr** [comment]
Hi @boniatillo-com 

No there is no guide. I'm using Eclipse IDE JEE Neon (so Java8 is required) and you need to import textmate.java too https://github.com/angelozerr/textmate.java

If you need more information, please post your question.

**Comment by angelozerr** [comment]
@boniatillo-com can I close this issue? Which helps do you need?

**Comment by angelozerr** [comment]
@boniatillo-com I close this issue. Reopen it if you need.

**Comment by boniatillo-com** [comment]
Ok thanks Angelo.
