### ISSUE TITLE
Install typescript IDE on Phaser Editor

### ISSUE THREAD

**Issue by boniatillo-com** [angelozerr/typescript.java#124]
When I try to install 1.1.0 o 1.2.0 on Phaser Editor (http://phasereditor.boniatillo.com/blog/downloads) it gives me the following warnings:

![image](https://cloud.githubusercontent.com/assets/12187299/21288821/e0a4b8f6-c45a-11e6-9675-1c4158de0c92.png)

Where do I should get that gson plugin?

I see in my dev eclipse installation it is present, but not needed for Phaser Editor so I guess I should add other update site somewhere.

**Comment by angelozerr** [comment]
gson comes when you install the Eclipse IDE JEE Neon.

**Comment by boniatillo-com** [comment]
It means that someone one to install TS IDE on a custom product what are the options?

- Do a repacking of TS IDE and include gson
- Add JEE Neon to the list of the update site

Does it make sense to package gson together with TS IDE? I guess it should work for both cases, custom and JEE distributions.

**Comment by angelozerr** [comment]
TS IDE requires JSDT which requires gson, no?

**Comment by boniatillo-com** [comment]
I see... maybe I am using an old version of JSDT with no gson dependency. 
Thanks!
