### ISSUE TITLE
Execute typescript.java from sources

### ISSUE THREAD

**Issue by micaelgallego** [angelozerr/typescript.java#13]
I want to contribute (as least as beta tester) in typescript.java project. 

I've downloaded a brand new eclipse distribution for plugin development. In concrete, I've downloaded "Eclipse IDE for Eclipse Committers 4.5.2".Then I've cloned the project and imported into Eclipse. But I get a lot of errors. What I'm doing wrong?

![image](https://cloud.githubusercontent.com/assets/1072424/13580880/7889e2f0-e4a4-11e5-9e24-4119fdedb801.png)

**Comment by angelozerr** [comment]
Try to import https://github.com/angelozerr/typescript.java/tree/master/thirdparties/minimal-json

**Comment by micaelgallego** [comment]
Thanks. Your advice reduce the compilation errors:

I still have the following errors:

**Project ts.eclipse.ide.jsdt.core:**
Bundle 'org.eclipse.wst.jsdt.core' cannot be resolved	MANIFEST.MF	/ts.eclipse.ide.jsdt.core/META-INF	line 12	Plug-in Problem
Bundle 'org.eclipse.wst.jsdt.ui' cannot be resolved	MANIFEST.MF	/ts.eclipse.ide.jsdt.core/META-INF	line 10	Plug-in Problem
Bundle 'org.eclipse.wst.sse.core' cannot be resolved	MANIFEST.MF	/ts.eclipse.ide.jsdt.core/META-INF	line 15	Plug-in Problem
Bundle 'org.eclipse.wst.sse.ui' cannot be resolved	MANIFEST.MF	/ts.eclipse.ide.jsdt.core/META-INF	line 17	Plug-in Problem
Bundle 'org.eclipse.wst.xml.core' cannot be resolved	MANIFEST.MF	/ts.eclipse.ide.jsdt.core/META-INF	line 16	Plug-in Problem

**ts.eclipse.ide.jsdt.ui:**
Bundle 'org.eclipse.wst.jsdt.core' cannot be resolved	MANIFEST.MF	/ts.eclipse.ide.jsdt.ui/META-INF	line 12	Plug-in Problem
Bundle 'org.eclipse.wst.jsdt.ui' cannot be resolved	MANIFEST.MF	/ts.eclipse.ide.jsdt.ui/META-INF	line 10	Plug-in Problem
Bundle 'org.eclipse.wst.sse.core' cannot be resolved	MANIFEST.MF	/ts.eclipse.ide.jsdt.ui/META-INF	line 18	Plug-in Problem
Bundle 'org.eclipse.wst.sse.ui' cannot be resolved	MANIFEST.MF	/ts.eclipse.ide.jsdt.ui/META-INF	line 20	Plug-in Problem
Bundle 'org.eclipse.wst.xml.core' cannot be resolved	MANIFEST.MF	/ts.eclipse.ide.jsdt.ui/META-INF	line 19	Plug-in Problem
Bundle 'org.eclipse.wst.xml.ui' cannot be resolved	MANIFEST.MF	/ts.eclipse.ide.jsdt.ui/META-INF	line 21	Plug-in Problem
The project was not built since its build path is incomplete. Cannot find the class file for org.eclipse.ui.texteditor.ITextEditor. Fix the build path then try building this project	ts.eclipse.ide.jsdt.ui		Unknown	Java Problem
The type org.eclipse.ui.texteditor.ITextEditor cannot be resolved. It is indirectly referenced from required .class files	JSDTEditorTracker.java	/ts.eclipse.ide.jsdt.ui/src/ts/eclipse/ide/jsdt/internal/ui/validation	line 1	Java Problem
Unknown extension point: 'org.eclipse.wst.jsdt.ui.javaCompletionProposalComputer'	plugin.xml	/ts.eclipse.ide.jsdt.ui	line 19	Plug-in Problem
Unknown extension point: 'org.eclipse.wst.jsdt.ui.javaCompletionProposalComputer'	plugin.xml	/ts.eclipse.ide.jsdt.ui	line 25	Plug-in Problem
Unknown extension point: 'org.eclipse.wst.jsdt.ui.javaEditorTextHovers'	plugin.xml	/ts.eclipse.ide.jsdt.ui	line 49	Plug-in Problem

**Project ts.eclipse.ide.server.nodejs.embed.linux.gtk.x86:**
Project 'ts.eclipse.ide.server.nodejs.embed.linux.gtk.x86' is missing required source folder: 'src/'	ts.eclipse.ide.server.nodejs.embed.linux.gtk.x86		Build path	Build Path Problem

**Project ts.eclipse.ide.validator.core:**
AbstractValidator cannot be resolved to a type	TypeScriptValidator.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 17	Java Problem
Bundle 'org.eclipse.wst.validation' cannot be resolved	MANIFEST.MF	/ts.eclipse.ide.validator.core/META-INF	line 16	Plug-in Problem
IMessage cannot be resolved to a variable	TypeScriptReporterCollector.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 61	Java Problem
IMessage cannot be resolved to a variable	TypeScriptReporterCollector.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 61	Java Problem
IReporter cannot be resolved to a type	TypeScriptReporterCollector.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 22	Java Problem
IReporter cannot be resolved to a type	TypeScriptReporterCollector.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 25	Java Problem
IReporter cannot be resolved to a type	TypeScriptReporterCollector.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 28	Java Problem
IReporter cannot be resolved to a type	TypeScriptReporterCollector.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 54	Java Problem
IReporter cannot be resolved to a type	TypeScriptValidationHelper.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/core/validation	line 14	Java Problem
IReporter cannot be resolved to a type	TypeScriptValidator.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 20	Java Problem
IReporter cannot be resolved to a type	TypeScriptValidator.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 25	Java Problem
IReporter cannot be resolved to a type	TypeScriptValidator.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 35	Java Problem
IValidationContext cannot be resolved to a type	TypeScriptValidator.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 25	Java Problem
IValidationContext cannot be resolved to a type	TypeScriptValidator.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 30	Java Problem
IValidationContext cannot be resolved to a type	TypeScriptValidator.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 35	Java Problem
IValidator cannot be resolved to a type	TypeScriptReporterCollector.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 23	Java Problem
IValidator cannot be resolved to a type	TypeScriptReporterCollector.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 25	Java Problem
IValidator cannot be resolved to a type	TypeScriptReporterCollector.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 29	Java Problem
IValidator cannot be resolved to a type	TypeScriptReporterCollector.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 54	Java Problem
IValidator cannot be resolved to a type	TypeScriptValidationHelper.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/core/validation	line 15	Java Problem
IValidatorJob cannot be resolved to a type	TypeScriptValidator.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 17	Java Problem
LocalizedMessage cannot be resolved to a type	TypeScriptReporterCollector.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 48	Java Problem
LocalizedMessage cannot be resolved to a type	TypeScriptReporterCollector.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 48	Java Problem
The import org.eclipse.wst cannot be resolved	TypeScriptReporterCollector.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 4	Java Problem
The import org.eclipse.wst cannot be resolved	TypeScriptReporterCollector.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 5	Java Problem
The import org.eclipse.wst cannot be resolved	TypeScriptReporterCollector.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 6	Java Problem
The import org.eclipse.wst cannot be resolved	TypeScriptReporterCollector.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 7	Java Problem
The import org.eclipse.wst cannot be resolved	TypeScriptValidationHelper.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/core/validation	line 3	Java Problem
The import org.eclipse.wst cannot be resolved	TypeScriptValidationHelper.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/core/validation	line 4	Java Problem
The import org.eclipse.wst cannot be resolved	TypeScriptValidator.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 6	Java Problem
The import org.eclipse.wst cannot be resolved	TypeScriptValidator.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 7	Java Problem
The import org.eclipse.wst cannot be resolved	TypeScriptValidator.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 8	Java Problem
The import org.eclipse.wst cannot be resolved	TypeScriptValidator.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 9	Java Problem
The import org.eclipse.wst cannot be resolved	TypeScriptValidator.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 10	Java Problem
Unknown extension point: 'org.eclipse.wst.validation.validatorV2'	plugin.xml	/ts.eclipse.ide.validator.core	line 32	Plug-in Problem
ValidationException cannot be resolved to a type	TypeScriptValidator.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 25	Java Problem
ValidationException cannot be resolved to a type	TypeScriptValidator.java	/ts.eclipse.ide.validator.core/src/ts/eclipse/ide/validator/internal/core/validation	line 35	Java Problem

**Project ts.eclipse.ide.validator.ui:**
Description	Resource	Path	Location	Type
Bundle 'org.eclipse.wst.sse.ui' cannot be resolved	MANIFEST.MF	/ts.eclipse.ide.validator.ui/META-INF	line 26	Plug-in Problem
Bundle 'org.eclipse.wst.validation.ui' cannot be resolved	MANIFEST.MF	/ts.eclipse.ide.validator.ui/META-INF	line 25	Plug-in Problem
Bundle 'org.eclipse.wst.validation' cannot be resolved	MANIFEST.MF	/ts.eclipse.ide.validator.ui/META-INF	line 24	Plug-in Problem
IReporter cannot be resolved to a type	TypeScriptSourceValidator.java	/ts.eclipse.ide.validator.ui/src/ts/eclipse/ide/validator/internal/ui/validation	line 30	Java Problem
IReporter cannot be resolved to a type	TypeScriptSourceValidator.java	/ts.eclipse.ide.validator.ui/src/ts/eclipse/ide/validator/internal/ui/validation	line 60	Java Problem
IReporter cannot be resolved to a type	TypeScriptSourceValidator.java	/ts.eclipse.ide.validator.ui/src/ts/eclipse/ide/validator/internal/ui/validation	line 75	Java Problem
ISourceValidator cannot be resolved to a type	TypeScriptSourceValidator.java	/ts.eclipse.ide.validator.ui/src/ts/eclipse/ide/validator/internal/ui/validation	line 25	Java Problem
IValidationContext cannot be resolved to a type	TypeScriptSourceValidator.java	/ts.eclipse.ide.validator.ui/src/ts/eclipse/ide/validator/internal/ui/validation	line 30	Java Problem
IValidationContext cannot be resolved to a type	TypeScriptSourceValidator.java	/ts.eclipse.ide.validator.ui/src/ts/eclipse/ide/validator/internal/ui/validation	line 75	Java Problem
IValidator cannot be resolved to a type	TypeScriptSourceValidator.java	/ts.eclipse.ide.validator.ui/src/ts/eclipse/ide/validator/internal/ui/validation	line 25	Java Problem
The import org.eclipse.wst cannot be resolved	TypeScriptSourceValidator.java	/ts.eclipse.ide.validator.ui/src/ts/eclipse/ide/validator/internal/ui/validation	line 7	Java Problem
The import org.eclipse.wst cannot be resolved	TypeScriptSourceValidator.java	/ts.eclipse.ide.validator.ui/src/ts/eclipse/ide/validator/internal/ui/validation	line 8	Java Problem
The import org.eclipse.wst cannot be resolved	TypeScriptSourceValidator.java	/ts.eclipse.ide.validator.ui/src/ts/eclipse/ide/validator/internal/ui/validation	line 9	Java Problem
The import org.eclipse.wst cannot be resolved	TypeScriptSourceValidator.java	/ts.eclipse.ide.validator.ui/src/ts/eclipse/ide/validator/internal/ui/validation	line 10	Java Problem
The import org.eclipse.wst cannot be resolved	TypeScriptSourceValidator.java	/ts.eclipse.ide.validator.ui/src/ts/eclipse/ide/validator/internal/ui/validation	line 11	Java Problem
The method connect(IDocument) of type TypeScriptSourceValidator must override or implement a supertype method	TypeScriptSourceValidator.java	/ts.eclipse.ide.validator.ui/src/ts/eclipse/ide/validator/internal/ui/validation	line 65	Java Problem
The method disconnect(IDocument) of type TypeScriptSourceValidator must override or implement a supertype method	TypeScriptSourceValidator.java	/ts.eclipse.ide.validator.ui/src/ts/eclipse/ide/validator/internal/ui/validation	line 70	Java Problem
Unknown extension point: 'org.eclipse.wst.sse.ui.sourcevalidation'	plugin.xml	/ts.eclipse.ide.validator.ui	line 18	Plug-in Problem
ValidationException cannot be resolved to a type	TypeScriptSourceValidator.java	/ts.eclipse.ide.validator.ui/src/ts/eclipse/ide/validator/internal/ui/validation	line 30	Java Problem

**Comment by angelozerr** [comment]
Please install Eclipse JEE distribution Mars.

**Comment by micaelgallego** [comment]
I've installed "Web Tools Platform SDK (WTP SDK) 3.1.2" using the update site "http://download.eclipse.org/webtools/updates" and a lot of errors are gone.

But there are still problems in the projects: 
* ts.eclipse.ide.server.nodejs.embed.linux.gtk.x86
* ts.eclipse.ide.server.nodejs.embed.linux.gtk.x86_64
* ts.eclipse.ide.server.nodejs.embed.macosx.cocoa.x86_64

The problems are:
Description	Resource	Path	Location	Type
* Project 'ts.eclipse.ide.server.nodejs.embed.linux.gtk.x86_64' is missing required source folder: 'src/'	
* Project 'ts.eclipse.ide.server.nodejs.embed.linux.gtk.x86' is missing required source folder: 'src/'	
* Project 'ts.eclipse.ide.server.nodejs.embed.macosx.cocoa.x86_64' is missing required source folder: 'src/'	

Thank you for your help.

**Comment by angelozerr** [comment]
> I've installed "Web Tools Platform SDK (WTP SDK) 3.1.2" using the update site "http://download.eclipse.org/webtools/updates" and a lot of errors are gone.

To clarify, typescript.java is based on JSDT Editor and WTP Validator. The most simply mean to have thoses plugins is to download "Eclipse JEE Distribution". But you will able to download light Eclipse distribution once the issue https://bugs.eclipse.org/bugs/show_bug.cgi?id=488781 will be finished.

> missing required source folder: 'src/'

I will add those folder to fix this error, but it's not a fatal error. You can ignore it. But in your workspace you need to import only the embed project according your OS (ex : import just ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64 if your OS is Windows 64 bits).

**Comment by micaelgallego** [comment]
Thank you for your help. Finally I have the source code without errors and can execute a Eclipse with TypeScript support.

**Comment by angelozerr** [comment]
Great! If you wish to do some (big) contribution, I think it should be cool if you could create issues in order to we disccuss it. If it's just to fix bugs, no need to create issue.

Please add too your name in the header of file that you will update.

Just one question, why do you wish to contribute to typescript.java although it exists eclipse-typescript, TypEcs which provide more features than typescript.java? Do you like the idea of JSDT Editor and tsserver?

**Comment by micaelgallego** [comment]
> Great! If you wish to do some (big) contribution, I think it should be cool if you could create issues in order to we disccuss it. If it's just to fix bugs, no need to create issue.

Perfect. First I need to learn some eclipse plugin development. But I'll do my best ;)

> Just one question, why do you wish to contribute to typescript.java although it exists eclipse-typescript, TypEcs which provide more features than typescript.java? Do you like the idea of JSDT Editor and tsserver?

The plugins you mention are not actively maintained right now. My main objective is develop Angular 2 applications with TypeScript in Eclipse, but these plugins are not working with Angular 2 (see https://github.com/axmor/typecs/issues/94). You have done an awesome with Angular 1 and tern.js plugins, and you are actively working on the plugin right now, It seems a good place to colaborate ;). On the other hand, if typescript plugin is directly using tsserver, It is more likely to be updated. And I hope JSDT integration will be good for TypeScript editor.

**Comment by angelozerr** [comment]
> Perfect. First I need to learn some eclipse plugin development. But I'll do my best ;)

At first you could create detailled issues in order to what you need (like tsc that I have started but not really usable)

> The plugins you mention are not actively maintained right now.

That's shame -( And what about eclipse-typescript?

> My main objective is develop Angular 2 applications with TypeScript in Eclipse,

Me too:) And I have doen the same integration like VSCode (to consume tsserver).

> You have done an awesome with Angular 1 and tern.js plugins, and you are actively working on the plugin right now

Thanks!

>  It seems a good place to colaborate ;). 

Cool!

> On the other hand, if typescript plugin is directly using tsserver, It is more likely to be updated.

Exactly! You need not to compile a custom bridge like TypEcs and eclipse-typescript have done. By default typescript.java provides a default TypeScript, but you can override it.

![typescriptserver](https://cloud.githubusercontent.com/assets/1932211/13605901/04d96d3e-e54a-11e5-9d44-1d23dec3d2f7.png)

I will try to update Wiki to explain more that.

> And I hope JSDT integration will be good for TypeScript editor.

Since RedHat guys are re-worked about JSDT project, I think it's a good idea. RedHat guys are very opened, are working hard to improve JSDT. Eclipse Neon will provide awesome like npm, bower and will host my JSON Editor too https://github.com/angelozerr/eclipse-wtp-json
