### ISSUE TITLE
Integrates tslint language service

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/typescript.java#133]
Integrates https://github.com/angelozerr/tslint-language-service

**Comment by angelozerr** [comment]
@lorenzodallavecchia if you are interested you can play with tslint but there are some problems again https://github.com/angelozerr/tslint-language-service/issues (create another issue if you need to this project).

To enable tslint, see https://github.com/angelozerr/typescript.java/wiki/TypeScript-Plugins

Many thanks for your feedback

**Comment by lorenzodallavecchia** [comment]
Thanks @angelozerr I'm definitely going to try that soon.
I like the way you are patching tsserver to add plugin support: really smart!

**Comment by angelozerr** [comment]
> I like the way you are patching tsserver to add plugin support: really smart!

Many thank's, but the main idea comes from https://github.com/Quramy/ng-tsserver/issues/1

**Comment by angelozerr** [comment]
Done 

![](https://github.com/angelozerr/typescript.java/wiki/images/TslintDemo.gif)

See https://github.com/angelozerr/typescript.java/wiki/New-and-Noteworthy-1.2.0#tslint-integration
