### ISSUE TITLE
Incoming dependent projects are not tracked by tsserver

### ISSUE THREAD

**Issue by lorenzodallavecchia** [angelozerr/typescript.java#140]
It looks like the in-memory view of a project by `tsserver` does not include other projects that depend on the project handled by the server.

For example, suppose to have
- a library project A,
- a specific project B that uses A for some work.

For files inside B, tsserver will correctly consider both A and B to be part of the compiler scope.
For files inside A, however, the compiler only sees A in the compiler scope.

That is correct for features like validationg a single file or showing content assist proposals.
However, features like _Compile on Save_ or _Search References_ may work incorrectly because of this.

## Steps to Reproduce

1. Import these [test projects](https://github.com/angelozerr/typescript.java/files/750714/TestProjects.zip).
2. In _shared-project/src/calculato.ts_, make the `sum` method private. An error correctly appears on _shared-project/src/main.ts_, but none appears on _specific-project/src/main.ts_. That is the bug.

## Workarounds (sort of)

A workaround is to modify _shared-project/tsconfig.json_ as follows.

```json
{
	"compilerOptions": {
		"target": "es5"
	},
	"compileOnSave": true,
	"include": [
		"src",
		"../specific-project/**/*"
	]
}
```

The include of `../specific-project/**/*` makes specific project part of the shared project compilation input. While this works technically, in practice it is not feasible because a shared library project cannot possibly list all client projects that may use it.

Another option is to include `../**/*`, but this raises concearns about performance of including all files of a potentially big workspace.

## Considerations

The workarounds are based on including dependent client code as it was _input_ code. While at first look this appears to work, it might cause problems, first of all by reducing performance (also, memory-wise).

It is possible that all these are tsserver limitations and so not easily solvable in typescript.java.

Please note that this issue does not reduce the value of `tsserver` integration. When using only a single tsconfig.json, the improvement in performance and dependency computation is simply not a match for the older `tsc`-based build.

**Comment by angelozerr** [comment]
@lorenzodallavecchia VSCode configure tsserver with some options that I have not understood https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/typescriptServiceClient.ts#L584 

I think it should be interesting to explore it. But for the moment very busy with https://github.com/angelozerr/typescript.java/issues/133

**Comment by lorenzodallavecchia** [comment]
@angelozerr don't worry about this issue for now: I'm even realizing that it is not written correctly.
I have looked into tsserver and the way you are integrating it and I think the overall approach is correct. There are a number of issues that may also be caused by tsserver limitations. Later today I will comment on #109 with a complete list.

**Comment by lorenzodallavecchia** [comment]
Closing, as the problem described here is a combination of separate problems.

Since the command is looking for references in the Eclipse **Project** it is correct that it does not work cross-project (that would be Workspace reference search). However, at least one file must be opened for each tsconfig.json scope in the same Eclipse project. See #142.

Workspace reference search requires a separate effort, probably similar to #144, for "merging" results from the tsserver's of all projects. I'll leave this unreported for now.
