### ISSUE TITLE
typescript.java searches wrong path for locally installed tsserver

### ISSUE THREAD

**Issue by nimo23** [angelozerr/typescript.java#141]
I installed ts 1.2.0-SNAPSHOT (and deleted old 1.1 from eclipse update site). I have tsc installed locally (v 2.1.5). When opening ts file in eclipse, this error occurs:

Cannot find [tsserver] file /usr/local/lib/node_modules/typescript/bin/tsc/bin/tsserver

When looking the path above, you see **"bin/tsc/bin/" which is wrong**. 

The right path is 
"/usr/local/lib/node_modules/typescript/**bin/tsc**" (for tsc) 
and 
"/usr/local/lib/node_modules/typescript/**bin/tsserver**" (for tsserver)

I use Mac OS. So I guess, typescript.java searches (local installed) tsserver/tsc with wrong path.

Please correct this. Thanks.

**Comment by angelozerr** [comment]
I I have understood you have configured `Installed TypeScript`  with `TypeScript / Runtime` project property with 

` /usr/local/lib/node_modules/typescript/bin/tsc`

But it should be 

` /usr/local/lib/node_modules/typescript`

Please not that typescript.java provides now `TypeScript 2.1.5` and `TypeScript 2.2.0 (rc)` as embedded TypeScript runtime.

**Comment by nimo23** [comment]
Okay, with `/usr/local/lib/node_modules/typescript` it works. Thanks!
