### ISSUE TITLE
TypeScript project Wizard

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/typescript.java#147]
Create a simple Wizard o create a TypeScript project which:

 * create an Eclipse project
 * generate a tsconfig.json from some fields (target, module, moduleResolution, other?)
 * add TypeScriptBuilder in the .project

@Springrbua please follow this issue.

**Comment by angelozerr** [comment]
@Springrbua the wizard is initialized. You can add fields like module, moduleResolution, target fields inside https://github.com/angelozerr/typescript.java/blob/master/eclipse/ts.eclipse.ide.ui/src/ts/eclipse/ide/internal/ui/wizards/TSConfigWizardPage.java

**Comment by Springrbua** [comment]
@angelozerr thanks a lot!

**Comment by angelozerr** [comment]
@Springrbua I have integrated your work and I have a little improved for teh tsconfig.json generation (generates only.json) fields which are managed by the wizard, ex : buildOnSave is not in the generated tsconfig

**Comment by Springrbua** [comment]
@angelozerr Thanks a lot! I'll recreate my repo
