### ISSUE TITLE
Improve editor experience to be similar to Java with JDT

### ISSUE THREAD

**Issue by micaelgallego** [angelozerr/typescript.java#15]
TypeScript.java plugin is in alpha state right now but also is improving quickly. 

In this issue I like only to note the differences between editor experience between Java with JDT and TypeScript with this plugin. 

* Mark ocurrences is missing. See [issue 17](https://github.com/angelozerr/typescript.java/issues/17).
* Semantic coloring in attributes (clear blue) and locals (brown) is missing. See [issue 18](https://github.com/angelozerr/typescript.java/issues/18).
* import and from are not colored as reserved words in import sentence. See [issue 19](https://github.com/angelozerr/typescript.java/issues/19).
* Navigate to type declaration, not to import. See https://github.com/angelozerr/typescript.java/issues/20
* Link with editor not working with TypeScript files. See https://github.com/angelozerr/typescript.java/issues/21 
* Autocomplete types not included in current scope with import autocomplete (as JDT does for Java). See
https://github.com/angelozerr/typescript.java/issues/22
* Collapse elements in editor (maybe imports can be collapsed automatically as JDT does for Java). See
https://github.com/angelozerr/typescript.java/issues/23
* Organize imports (remove unnecessary imports). See
https://github.com/angelozerr/typescript.java/issues/24
* Refresh project when creating duplicate file (it is necessary to refresh explicitly to see new file). See
https://github.com/angelozerr/typescript.java/issues/25
* File icon in project explorer doesn't show compile error icon when there is an error in the file. See
https://github.com/angelozerr/typescript.java/issues/26
* Compilation errors don't appear in Problems view. See
https://github.com/angelozerr/typescript.java/issues/27
* Refactor rename is not working. When use Ctrl+R appears a dialog error with message "Operation unavailable in the current selection". See
https://github.com/angelozerr/typescript.java/issues/28
* Ctrl+Shift+T is not working for finding types. See
https://github.com/angelozerr/typescript.java/issues/29
* Hover when autocompleting shows `<pre>` and `</pre>` in the text. See
https://github.com/angelozerr/typescript.java/issues/30 
* Autocompleting is not working in import path. (see https://github.com/Microsoft/TypeScript/issues/188). See
https://github.com/angelozerr/typescript.java/issues/31
* In JDT when going to declaration, only the name of the element is selected. In TypeScript.java, all class or method is selected. The behavior should be the similar to JDT. See
https://github.com/angelozerr/typescript.java/issues/32
* Open Call hierarchy shows error "The resource is not on the build path of JavaScript project". See
https://github.com/angelozerr/typescript.java/issues/33
* Open Type Hierarchy shows error "The resource is not on the build path of JavaScript project". See
https://github.com/angelozerr/typescript.java/issues/34
* TypeScript editor is referred as "JavaScript editor" when open a file. See
https://github.com/angelozerr/typescript.java/issues/35
* Format code doesn't work. See
https://github.com/angelozerr/typescript.java/issues/36
* In JDT when select a method from autocomplete list, parenthesis are write to code, and the parameter names (from documentation/source code) are write and selected (to edit them). In methods with several parameters, every parameter is boxed and developer can navigate with tabs between them. In TypeScript only method name is write. See
https://github.com/angelozerr/typescript.java/issues/37
* Outline is missing for TypeScript files. See
https://github.com/angelozerr/typescript.java/issues/38

@angelozerr Do you prefer that I open an issue for every item in the list to further discussion or is ok for now to have the list registered here?

**Comment by angelozerr** [comment]
> @angelozerr Do you prefer that I open an issue for every item in the list to further discussion or is ok for now to have the list registered here?

Thanks @micaelgallego for having taking time to list (a lot of) issues. I think it should be better to have an issue per problem for the discussion.

**Comment by micaelgallego** [comment]
Ok thanks, I'll do it when I have a bit time to put more details in every issue.

**Comment by micaelgallego** [comment]
I've just created an independent issue for every item in this list. Maybe we can close this issue to track th work on the new ones.

**Comment by angelozerr** [comment]
Thanks @micaelgallego I close this issue.
