### ISSUE TITLE
Tab width preferences not working for TS editor

### ISSUE THREAD

**Issue by SpliFF** [angelozerr/typescript.java#154]
I'm trying to follow the (god-awful) angular2 convention where .ts files are indented using 2 spaces.

Using Neon.2 Release (4.6.2) I have tried every preference pane option related to formatting tabs but I always get 4 spaces when I press tab. 

More specifically I have done:
Preferences -> Javascript -> TypeScript -> Editor -> Formatter
Editor Options
[Ticked] Whether tabs should be converted to spaces
Number of spaces to indent during formatting [2]
Number of spaces for each tab [2]

I also tried exporting and re-importing preferences from the following .epf file:

```
file_export_version=3.0
/instance/org.eclipse.wst.jsdt.core/org.eclipse.wst.jsdt.core.formatter.indentation.size=2
/instance/org.eclipse.jdt.ui/org.eclipse.jdt.ui.editor.tab.width=2
/instance/org.eclipse.jdt.ui/tabWidthPropagated=true
/instance/org.eclipse.ui.editors/tabWidth=2
/instance/org.eclipse.wst.jsdt.core/org.eclipse.wst.jsdt.core.formatter.tabulation.char=space
/instance/org.eclipse.wst.jsdt.core/org.eclipse.wst.jsdt.core.formatter.tabulation.size=2
/instance/org.eclipse.wst.jsdt.core/org.eclipse.wst.jsdt.core.formatter.use_tabs_only_for_leading_indentations=false
/instance/org.eclipse.wst.jsdt.ui/org.eclipse.wst.jsdt.ui.editor.tab.width=2
/instance/org.eclipse.wst.jsdt.ui/smart_tab=false
/instance/org.eclipse.wst.jsdt.ui/tabWidthPropagated=true
```

I still get a tab width of 4 spaces. 
Auto indents are 4 spaces. 
Source -> Format (Ctrl + Shift + F) sets leading indents to 4 spaces. 

When I open a .ts file the editor shows a [ts] icon on the tab label so I am definitely using the Typescript editor.  It just seems like the Typescript editor doesn't actually use the spacing preferences it provides.

**Comment by angelozerr** [comment]
TypeScript Editor has own preferences for formatter (don't use JSDT format preferences, don't use UI editor preferences).

It uses only `Javascript -> TypeScript -> Editor -> Formatter`

It should working with 1.2.0-SNAPSHOT. Which version are you using?

**Comment by SpliFF** [comment]
It says 1.1.0. I ran a full update yesterday. I think I have the wrong update site though because the repo is `http://oss.opensagres.fr/angular2-eclipse/1.1.0/`. Where should I be getting the snapshot version from?

**Comment by SpliFF** [comment]
Thanks. Updating to 1.2.0-SNAPSHOT fixed the issue.
