### ISSUE TITLE
Eclipse auto build output directory problem

### ISSUE THREAD

**Issue by sfkristof** [angelozerr/typescript.java#155]
When saving a "ts" source file in Eclipse the auto TS build runs but it puts the compiled
"js" file just to the root output directory given in the "tsconfig.json" config file, instead
of using (or creating) the same directory structure under the "bin" directory.
While if I right click on the "tsconfig.json" file in the "Package Explorer" and do a
"Run as / Compile TypeScript" the the "js" files are generated in the expected place.

What is wrong? Is it a plugin bug or maybe just a configuration issue?

Example:
TypeScript source file:
c:\workspace\project\src\main\resources\META-INF\resources\interface\modulname\components\PhaseData.ts 

Ctrl + s

TypeScript compiled file:
c:\workspace\project\bin\META-INF\resources\PhaseData.js 

Content of the "tsconfig.json": (location: c:\workspace\project\tsconfig.json)
{
    "compilerOptions": {
        "module": "amd",
        "moduleResolution" : "node",
        "sourceMap": false,
        "target": "es5",
        "noImplicitAny": false,        
        "inlineSourceMap": true,
        "inlineSources": true,        
        "skipLibCheck": true,
        "outDir": "bin/META-INF/resources",        
        "baseUrl": "./src/main/resources/META-INF/resources/",
        "declaration": true,
        "declarationDir": "../node_modules"        
    },
    "compileOnSave": true,
    "buildOnSave": false,
    "exclude": [
        "bin",
        "build"
    ],
    "include": ["src/**/*.ts","src/**/*.d.ts","src/**/*.tsx"]
}

Thanks in advance!

Cheers,
  Kristof

**Comment by angelozerr** [comment]
- At first I suggest you that you use 1.2.0-SNAPSHOT.

 - Your tsconfig.json should be:

```
"include": [
		"src/**/*.ts",
		"src/**/*.d.ts",
		"src/**/*.tsx"
	]
```

It should work.

**Comment by sfkristof** [comment]
Ok, thanks, we check the version 1.2.0.
(Regarding the "include" section: it is exactly like you wrote it I just forgot to use the "pre" tag and the UI took it as a comment...)

**Comment by sfkristof** [comment]
Thanks a lot Angelo, updating the plugin to v1.2.0 solved the problem! ;)
