### ISSUE TITLE
JSX editor requires .jsx file extension 

### ISSUE THREAD

**Issue by houston3** [angelozerr/typescript.java#157]
JSX editor seems to work only if file extension is .jsx. It should work the same regardless of file name.
For example if I have a JSX file with extension .js and use "Open with" -> "JSX editor" or associate JSX editor with .js files, the editor opens but highlighting and suggestions don't work. See attachments.

![index-js](https://cloud.githubusercontent.com/assets/1021668/23647922/0baab9d8-0321-11e7-972f-afb03f4a3f01.png)
![index-jsx](https://cloud.githubusercontent.com/assets/1021668/23647923/0bf7ca3e-0321-11e7-85b3-537e45aa4780.png)

**Comment by angelozerr** [comment]
I will study this problem when I will find time.

Why do you want to use "js" extension for "jsx"?

**Comment by rivasd** [comment]
I would like to use this feature too for compatibility with [the create-react-app utility](https://github.com/facebookincubator/create-react-app/issues/87) which requires files ending in the .js extension. The discussion's point is that editors and compiler should be adaptable to the variety of syntaxes in the JavaScript -framework worlds.

**Comment by angelozerr** [comment]
Ok I see. Thanks for linking this info.

I know tsserver can support that. Problem is about editor. Just find time to study that.

**Comment by angelozerr** [comment]
@houston3 once https://opensagres.ci.cloudbees.com/job/typescript.java/353/ will be finished, please install 1.3.0-SNAPSHOT with update site https://github.com/angelozerr/typescript.java/wiki/Installation-Update-Site

Everything is managed with content type:

 * you can for instance add `*.es6` to the JSX content type to consider that `*.es6` are JSX.
 * you can for instance add `*.js` to the JSX content type to consider that `*.js` are JSX.

You will have problem with syntax coloration for '*.js', I suggest you that you use TextMate to avoid this problem.

Tell me if it works for you.

**Comment by angelozerr** [comment]
@houston3 could you tell me if it works for you? Thanks

**Comment by angelozerr** [comment]
None answer, I close this issue. @houston3 if you have again problem please reopen this issue.
