### ISSUE TITLE
Unable to Install Joni 2.1.11.v20170306-1742

### ISSUE THREAD

**Issue by davidlecce** [angelozerr/typescript.java#158]
Cannot complete the install because one or more required items could not be found.
  Software being installed: Joni 2.1.11.v20170306-1742 (org.joni 2.1.11.v20170306-1742)
  Missing requirement: Joni 2.1.11.v20170306-1742 (org.joni 2.1.11.v20170306-1742) requires 'package org.objectweb.asm 5.0.3' but it could not be found

Joni is required to update TextMate

Cannot complete the install because one or more required items could not be found.
  Software being installed: TextMate Core 0.1.0.201703091113 (tm-feature.feature.group 0.1.0.201703091113)
  Missing requirement: Joni 2.1.11.v20170306-1742 (org.joni 2.1.11.v20170306-1742) requires 'package org.objectweb.asm 5.0.3' but it could not be found
  Cannot satisfy dependency:
    From: TextMate support in Eclipse IDE - Core 0.1.0.201703091113 (org.eclipse.tm4e.core 0.1.0.201703091113)
    To: bundle org.joni 2.1.11
  Cannot satisfy dependency:
    From: TextMate Core 0.1.0.201703091113 (tm-feature.feature.group 0.1.0.201703091113)
    To: org.eclipse.tm4e.core [0.1.0.201703091113]

**Comment by angelozerr** [comment]
Since tm4e was migtated to Eclipse.org, typescript.java and angular2-eclipse have this problem.

In other words, @davidlecce please be patient. 

@pascalleclercq could you work about this issue please. Thanks!

**Comment by pascalleclercq** [comment]
Apparently, org.objectweb.asm is missing for the repository.


I'll add It ASAP.

**Comment by pascalleclercq** [comment]
Done !

**Comment by angelozerr** [comment]
Thank a lot @pascalleclercq! Please fix this issue for angular2 eclipse. Thanks!

**Comment by angelozerr** [comment]
Problem was posted for Angular2 Eclipse at https://marketplace.eclipse.org/comment/4426#comment-4426
