### ISSUE TITLE
Component bindings not working in HTML

### ISSUE THREAD

**Issue by allurefx** [angelozerr/typescript.java#159]
Bindings in HTML don't seem to be working for components. For @Input values, there is no auto-complete and a "Undefined ng property binding" warning appears (E.g., [root]='whatever' in ionic). For @Output values, there is no auto-complete and a "Undefined ng event binding" warning appears.

Sample HTML that triggers these warnings:
1. <ion-tab [root]='whatever'></ion-tab>
2. <app-park (trigger)='act($event)'></app-park>

**Comment by angelozerr** [comment]
It seems that your issue is for https://github.com/angelozerr/angular2-eclipse/

Please recreate this issue if it that.

**Comment by allurefx** [comment]
Sure, opened it there, thanks.
