### ISSUE TITLE
Embedded TypeScript not found

### ISSUE THREAD

**Issue by boniatillo-com** [angelozerr/typescript.java#164]
Hi, I am launching typescript from code but it does not find the embedded typescript installation.

![image](https://cloud.githubusercontent.com/assets/12187299/24408296/37256c4a-139b-11e7-94ab-92d86cb1440f.png)

I confirm the plugin `ts.repository` is installed, but it looks like the extension is not loaded.

Am I missing something?

**Comment by angelozerr** [comment]
@boniatillo-com that's very strange because other users seems hav enot this problem? Perhaps your installation was not done completely? Have you a plugin.xml in your ts.repository?

**Comment by boniatillo-com** [comment]
I did a fresh install and it works, thanks.
