### ISSUE TITLE
Cannot create TypeScript project

### ISSUE THREAD

**Issue by boniatillo-com** [angelozerr/typescript.java#166]
I just installed the 1.2.0 snapshot and I cannot create a project. Here I attach the screenshot of the console log. When I press Next, to start with the project wizard, it does nothing.

I did not installed the embedded node, I am used the one is installed in the OS, but if I create the `tsconfig.json` file manually and add it to the build path it seems to work.

![image](https://cloud.githubusercontent.com/assets/12187299/24456203/4b5f3de2-1460-11e7-9292-5d980b84729e.png)

**Comment by angelozerr** [comment]
@boniatillo-com this wizard is under dev, it is not finished.

> I did not installed the embedded node,

Never tested with this config. I will try to think about this pb now.

**Comment by angelozerr** [comment]
@boniatillo-com I have done a fix. Please tell me if it works for you. Thanks!

**Comment by boniatillo-com** [comment]
I will try tomorrow morning. Thanks.

**Comment by boniatillo-com** [comment]
No, not working yet.

![image](https://cloud.githubusercontent.com/assets/12187299/24551163/7ce44994-15ef-11e7-996a-ee80f6aff087.png)

**Comment by boniatillo-com** [comment]
I am trying to install the Embed Node.js but I get this error:

```
An error occurred while collecting items to be installed
session context was:(profile=C__Users_arian_Documents_Bin_jee-neon_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at http://oss.opensagres.fr/typescript.ide/1.2.0-SNAPSHOT/plugins/ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64_1.2.0.201703251317.jar.
Premature end of Content-Length delimited message body (expected: 10753066; received: 1553789
```

But probably it is because my internet connection at this time of the day.

**Comment by angelozerr** [comment]
It's the same stack trace that the first. So you have not the last version of 1.2.0-SNAPSHOT

**Comment by angelozerr** [comment]
@boniatillo-com had you time to reinstall 1.2.0-SNAPSHOT? If you have the same problem, please unisntall reinstall 1.2.0-SNAPSHOT. Thanks!

**Comment by boniatillo-com** [comment]
Sorry @angelozerr I thought I closed this issue.

Uninstall/install not worked, but update worked. For sure it was an Eclipse related problem, not a typescript.java one. So I close this issue because it worked for me.

Sorry again.

**Comment by angelozerr** [comment]
> Sorry again.

No pb @boniatillo-com I try just to close issues:)
