### ISSUE TITLE
Mark occurrences is missing.

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/typescript.java#17]
Mark ocurrences is missing.

**Comment by angelozerr** [comment]
@micaelgallego  could you give me a sample which doesn't work? In my case it works for variable. 

I know that tsserver provides a service to so that. We have 2 choices:

 * waiting for support of mark occurences for ES6  https://bugs.eclipse.org/bugs/show_bug.cgi?id=489897
 * if it's not enough waiting for the capaibity to override mark occurence https://bugs.eclipse.org/bugs/show_bug.cgi?id=490429

**Comment by micaelgallego** [comment]
Effectively "Mark occurrences" works for variables. But only for variables ;)

Screenshot working for variables:
![image](https://cloud.githubusercontent.com/assets/1072424/14048019/d575b7a4-f2ab-11e5-88d5-1ae0524de83b.png)

Screenshot not working for methods:

![image](https://cloud.githubusercontent.com/assets/1072424/14048045/05de8c5e-f2ac-11e5-8c62-4f8d3eaad6db.png)


Screenshot not working for attributes:

![image](https://cloud.githubusercontent.com/assets/1072424/14048038/f8513780-f2ab-11e5-9862-46d9659c176d.png)

**Comment by micaelgallego** [comment]
Is there any service in tsserver to implement this behavior?

**Comment by angelozerr** [comment]
Yes I think, but I must study it.

**Comment by angelozerr** [comment]
@micaelgallego I have implemented "Mark occurrences" by consumming tsserver with "occurrences" command. It works well except that it freezes Eclipse when editor got the focus and tsserver is not started. I must improve really that by consumming tsserver with asynch mean (hope it will work).

**Comment by angelozerr** [comment]
Mark occurrences os now done with async to avoid freezing Eclipse

![Mark Occurrences](https://github.com/angelozerr/typescript.java/wiki/images/TypeScriptMarkOccurrences.png)

See https://github.com/angelozerr/typescript.java/wiki/Editor-Features#mark-occurrences for more information
