### ISSUE TITLE
Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning

### ISSUE THREAD

**Issue by bennycho** [angelozerr/typescript.java#173]
I have set tsconfig.json, when I edit  typescript file , it will appear "Experimental support for decorators is a feature that is subject to change in a future release. Set The 'experimentalDecorators' option to remove this warning. My tsconfig.json already set 'experimentalDecorators' is true, I have found the program execution will go to tsserver.js, generate the error message, and it regenerates the information that was already set in tsconfig.json because it executes  "function ProjectService.prototype.refreshInferredProjects" , but I do not know which side of the implementation of the call ProjectService, Can you tell me where you are calling tsserver this part of the program? I can help find the problem, thank you.

**Comment by angelozerr** [comment]
I close this issue since it's an issue to TypeScript tsserver. Please create an issue to TypeScript project. Thanks!
