### ISSUE TITLE
Navigate Annotation

### ISSUE THREAD

**Issue by wolfgang-ch** [angelozerr/typescript.java#182]
Missing feature to navigate to next/previous annotation with `<ctrl>.` and `<ctrl>,` 
This feature is available for some file types (but not .ts) in Eclipse which makes it easily to navigate to issues in the file.

**Comment by angelozerr** [comment]
Please install 1.3.0-SNAPSHOT and tell me if it works now. Thanks!

**Comment by wolfgang-ch** [comment]
perfekt 👍
