### ISSUE TITLE
Syntax colouring does not respect theme

### ISSUE THREAD

**Issue by eliasvasylenko** [angelozerr/typescript.java#184]
The non-TextMate syntax colouring for jxs files does not seem to respect the current theme for the colour of tags and attributes. Is there a way to change these colours?

**Comment by angelozerr** [comment]
No it's not possible. I have no time to support this feature. My idea is to switch to TextMate by default once tm4e will have more feedback.

**Comment by eliasvasylenko** [comment]
Okay no problem, I suspected this might be the case, just thought I'd ask in case :) cheers
