### ISSUE TITLE
import and from are not colored as reserved words in import sentence. 

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/typescript.java#19]
import and from are not colored as reserved words in import sentence.

**Comment by angelozerr** [comment]
import and from comes from ES6 syntax. JSDT is improving syntax coloration for ES6. It will be available for Eclipse Neon (in June).

**Comment by micaelgallego** [comment]
With your brand new TypeScript editor what do you think about this issue?

**Comment by angelozerr** [comment]
The TypeScript editor uses syntax coloration of JSDT (which is a big part). You must wait Neon for import.

**Comment by angelozerr** [comment]
Fixed with https://github.com/angelozerr/typescript.java/commit/b4f3bfa0286fad8b37a036b3c9d48d35a6d5c5c8

**Comment by angelozerr** [comment]
Here the result:

![](https://github.com/angelozerr/typescript.java/wiki/images/TypeScriptSyntaxColorForKeyWordsAndDecorator.png)

See https://github.com/angelozerr/typescript.java/wiki/New-and-Noteworthy-1.1.0#typescript-editor
