### ISSUE TITLE
cannot integrate tslint plugin

### ISSUE THREAD

**Issue by stefanholzmueller** [angelozerr/typescript.java#191]
TypeScript IDE works quite good (great progress over the last few months!), but I cannot get any tslint errors in Eclipse. Not sure if it is a problem with typescript.java or tslint-language-service, but since I configured everything according to https://github.com/angelozerr/typescript.java/wiki/TypeScript-Plugins#enable-tslint I use this issue tracker here.

After struggling with the config for a while, I set up a minimal self-contained project and it does not work, too. Basically, I did:

- Create new Typescript project in Eclipse
- npm install --save-dev typescript tslint tslint-language-service
- tsconfig.json
```
    {
	"compilerOptions": {
    		"plugins": {
		    	"name": "tslint-language-service"
	    	}
    	}
    }
```
- tslint.json
```
    {
        "rules": {
            "quotemark" : [ true, "single"]
        }
    }
```
- test.ts
`let a = "";`

Some hints:

- I tried both the embedded runtime (which is supposed to work directly) and a locally installed one - no difference.
- I do not see anything about tslint when I enable tracing of tsserver communication.
- I use Eclipse Neon (4.6.2) and Windows 7.

Is there anything I missed? How to debug this problem? Thanks.

**Comment by angelozerr** [comment]
Have you tried tout create project with wizard

**Comment by stefanholzmueller** [comment]
Yes for the minimal project, and I compared the created files with my actual project, and did not spot any relevant difference. Is there anything I should look out for?

**Comment by angelozerr** [comment]
Project with wizard is working? You must use type script 2.4.1 and typrscripy tslint tslint_language-service in the ode_modules folder of your project. If you have problem please share jour project

**Comment by stefanholzmueller** [comment]
It works now... turns out my tsconfig.json was wrong (some square brackets were missing). I believe it was caused by the formatter (see #193).
