### ISSUE TITLE
Formatter for tsconfig.json changes JSON structure

### ISSUE THREAD

**Issue by stefanholzmueller** [angelozerr/typescript.java#193]
I copy/pasted this configuration for tslint into the "compilerOptions" section of my tsconfig.json:
```
"plugins": [ { "name": "tslint-language-service" } ]
```
... and afterwards formatted the file with Ctrl-Shift-F:
```
    "plugins": {
      "name": "tslint-language-service"
    }
```
(note the missing square brackets!)

Depending on the cursor position, other effects may happen, e.g. duplication or deletion of parts of the file.

This was the root cause of #191

**Comment by stefanholzmueller** [comment]
> The formatting behaviour is done by calling format command of the tsserver. If you find a bug, with formatting, please check with VSCode if it has the same problem.

Formatting works fine in VSCode.

**Comment by angelozerr** [comment]
JSON editor comes from eclipse wtp. Have you tried with oxygène? Otherwise please create a bug to eclipse bugzilla
