### ISSUE TITLE
Go to Matching Bracket (Ctrl+Shift+P )

### ISSUE THREAD

**Issue by marsiancba** [angelozerr/typescript.java#197]
The key combination works in most other editors (java,php,js, ....) but not in TS, at least for me (using 1.4 SNAPSHOT).

**Comment by angelozerr** [comment]
Indeed it was not implemented. Please reinstall 1.4.0-SNAPSHOT with update site http://oss.opensagres.fr/typescript.ide/snapshots/ Please note this url could be change in few days with http://oss.opensagres.fr/typescript.ide/snapshot/

**Comment by marsiancba** [comment]
Wow, that was fast! It works, thank you.

One (marginally) related question: When you select an item (e.g. class/function) in the editor with Ctrl+O (or with Outline view), it will select whole body of class/function instead of selecting just name (like in other editors). Is there some logic behind this different behavior?
