### ISSUE TITLE
File not transpiled to JS when the filename ends with a 'd'

### ISSUE THREAD

**Issue by NielsNet** [angelozerr/typescript.java#199]
There seems to be an error concerning files with a 'd' as last character in the filename.  
E.g.: When a file is called `myFile.ts` everything works fine and a `myFile.js` is created, but when it is called `myFiled.ts` it is not transpiled and there is no `myFiled.js`.  
I suspect that there is a problem with the logic that should find description files. Maybe you're looking for `*d.ts` instead of `*.d.ts`?

**Comment by angelozerr** [comment]
Indeed it was a stupid error. Good catch! Thanks.

**Comment by NielsNet** [comment]
Thank you for the quick response and fix 👍
