### ISSUE TITLE
Code marked as comment

### ISSUE THREAD

**Issue by NielsNet** [angelozerr/typescript.java#203]
When writing code there seems to be an error with the syntax highlighting.  
As soon as you use two or more letters with an umlaut in an inline-comment the next line is marked as a comment in the editor.  
```typescript
[...]
//As an example: in Eclipse the next line will be gray just like this line when I add äö
let test = null;
[...]
```
It doesn't matter where the comment is placed, nor where the letters with an umlaut are placed within the comment.

**Comment by NielsNet** [comment]
I just tried out some test cases.  
For me there is a problem with single-line comments and two or more umlauts and with multiline/JSDoc comments and three or more umlauts.
![grafik](https://user-images.githubusercontent.com/30441612/29863247-5a355f4e-8d6f-11e7-9879-abd29af604ca.png)

**Comment by angelozerr** [comment]
Could you create this issue at https://github.com/eclipse/tm4e/ and set the code  which causes problem in the issue. Thanks!

**Comment by angelozerr** [comment]
I have tried to fix this bug width https://github.com/eclipse/tm4e/commit/f711b76b6cd5460b16ee84abbd04281701eed87a 

I close this issue since it's a bug with tm4e.
