### ISSUE TITLE
To keep completion proposals similar to JSDT

### ISSUE THREAD

**Issue by boniatillo-com** [angelozerr/typescript.java#204]
Hi,

The completion proposals on TypeScript IDE are different to the JSDT one:

The good old Eclipse (JSDT) style:

![image](https://user-images.githubusercontent.com/12187299/29894263-b8871f3c-8da2-11e7-8acd-4027e5498f9e.png)

The new TypeScript IDE style:

![image](https://user-images.githubusercontent.com/12187299/29894270-c157a154-8da2-11e7-92fc-47c91a6182d9.png)

* Show the method arguments, return type and declaring class in the proposals list.
* Show the right icons in the proposals list.
* Show the bold/black font on the method signature of the proposal's info window.

I think to keep close to the Eclipse (JSDT) style is a good idea. Actually I am voting for it in this TM4E issue: https://github.com/eclipse/tm4e/issues/131

**Comment by angelozerr** [comment]
> Show the method arguments, return type and declaring class in the proposals list.

Not sure that tsserver supports that?

> Show the right icons in the proposals list.

Yes sure.

> Show the bold/black font on the method signature of the proposal's info window.

You mean when you use Eclipse Dark theme? If that yes it should be supported.

Just find time to do that.

**Comment by boniatillo-com** [comment]
> You mean when you use Eclipse Dark theme? If that yes it should be supported.
I mean the first line in the info window is bold and black in JSDT, but in TypeScript IDE it is blue.

> Not sure that tsserver supports that?
I think yes, I did a test and it shows the method return type and declaring class:

![image](https://user-images.githubusercontent.com/12187299/29921921-90820270-8e21-11e7-851c-8508ef456b9d.png)

**Comment by angelozerr** [comment]
> I mean the first line in the info window is bold and black in JSDT, but in TypeScript IDE it is blue.

Yes I do the same thing than VSCode, I parse the result of quickinfo with TextMate parser. I prefer following logic of VSCode.

> I think yes, I did a test and it shows the method return type and declaring class:

TypeScript IDE does the same thing:

![image](https://user-images.githubusercontent.com/1932211/29922071-6433b942-8e54-11e7-8309-8a3e0dba3887.png)

**Comment by boniatillo-com** [comment]
Yes you are right, VSCode only shows the extra info of the selected proposal. Actually the `completions` command only provides the names of the members. So if we want to show, in the proposals list all the info then we have to request a `completionEntryDetails` for each proposal.

By the way, do you know if tsserver supports a batch of requests?

**Comment by boniatillo-com** [comment]
Well, in the `tsserver` issue: https://github.com/Microsoft/TypeScript/issues/18179

They say they are not going to implement it because it could be too much heavy to compute, so I fear that alternative solutions like get the details of the first 100 completions could be implemented in the client side.

Probably I will do this in the Phaser Editor side :), it is fine if for the moment TypeScript IDE redirect its effort in other fields.

Thanks!

**Comment by angelozerr** [comment]
A similatr issue was posted for netbeans https://github.com/Microsoft/TypeScript/issues/13647 

In otherwords, I prefer following the same behaviour than VSCode than try to have an Eclipse JSTDT/JDT behaviour.
