### ISSUE TITLE
Link with editor not working with TypeScript files

### ISSUE THREAD

**Issue by micaelgallego** [angelozerr/typescript.java#21]

**Comment by angelozerr** [comment]
That's strange it works for me?

**Comment by micaelgallego** [comment]
There is no error in "Errors log".

![anim](https://cloud.githubusercontent.com/assets/1072424/13728106/eda03e2e-e90c-11e5-8996-291ae8703f28.gif)

**Comment by angelozerr** [comment]
Could you retest please with the new TypeScript Editor? Thanks

**Comment by micaelgallego** [comment]
Fixed
