### ISSUE TITLE
Some thoughts about TsconfigEditor

### ISSUE THREAD

**Issue by boniatillo-com** [angelozerr/typescript.java#215]
Hi,

A tsconfig.json editor could be very helpful because the user does not need to read the documentation to changes its values. In addition, the json file is generated with a correct syntax...

However, an outdated or incomplete TsconfigEditor could be confusing or counterproductive for the user, because at the end the user is forced to write directly on the json file.

We always have the option to keep the TsconfigEditor updated and complete but it is an extra effort.

I think to keep a simple JSON editor ( and a link to the tsconfig.json specs) could be a more practical solution. At the end, this is what other editors (like VSCode) does.  

What do you think?

**Comment by angelozerr** [comment]
> A tsconfig.json editor could be very helpful because the user does not need to read the documentation to changes its values. In addition, the json file is generated with a correct syntax...

You don't like https://github.com/angelozerr/typescript.java/wiki/TSConfig-Editor-Features ?

There is a Source tab where you can type your JSON content and it uses WTP JSON Schema to benefit with completion.

**Comment by boniatillo-com** [comment]
Yes, I love that Source tab! It is a great work, the UI part is the one I think is hard to keep updated. The only thing I would like to add to the "source" editor is the proposals of the file names of the project.

The jsconfig files are not a complex stuff, like for example a plugin.xml of PDE, they can be edited very well with textual editors.

Sure, these are some thoughts and a personal preference.

**Comment by angelozerr** [comment]
> Yes, I love that Source tab!

Cool:)

> The jsconfig files are not a complex stuff

We should provide this editor by extending the TSConfigEditor or extract some commons code.
