### ISSUE TITLE
Files with (at least) "field" in their name do not compile (on save)

### ISSUE THREAD

**Issue by danielvanmil** [angelozerr/typescript.java#216]
- create a file named "field.ts" or a file that does have at least "field" in its name like also "xx-field.ts".
- change the file
- no .js file is generated?

When performing a full compile by the tsconfig.json  -> Run as -> Compile Typescript the files are generated properly.

Could this have something to do with a keyword in the file name?

**Comment by angelozerr** [comment]
Check:

 * you have activated TypeScript builder (open tsconfig.json editor for that)
 * declare compileOnSave to true (open tsconfig.json editor for that too)

**Comment by danielvanmil** [comment]
it only happens with the file named with "field" in the name, other files compile as usual.

**Comment by angelozerr** [comment]
Which version of typescript.java, which version TypeScript Runtime do you use? It works for me.

**Comment by danielvanmil** [comment]
new pc/lap -> cannot reproduce (as you probably expected, but it still is a strange thing)
