### ISSUE TITLE
[ES6] Auto imports with completion

### ISSUE THREAD

**Issue by micaelgallego** [angelozerr/typescript.java#22]

**Comment by angelozerr** [comment]
Could you give a sample please?

**Comment by micaelgallego** [comment]
In Java, if you write "ArrayL" and press Ctrl+Space to trigger autocomplete, JDT suggest you "java.util.ArrayList" and if you select in the proposal, "ArrayList" is written to source code and the import is included in the compilation unit. In Typescript.java, if you try start writing "Fig" in a project with the class "Figure" (in the module "Figure.ts"), no suggestions appear. I suppose that this is a limitation of tsserver. 

![anim](https://cloud.githubusercontent.com/assets/1072424/13728082/bc6cc170-e90b-11e5-8bf8-96a56b398feb.gif)

**Comment by angelozerr** [comment]
Please suggest your idea to TypeScript https://github.com/Microsoft/TypeScript/issues

**Comment by angelozerr** [comment]
It seems TypeScript 2.4 will provide this feature. See PR at https://github.com/Microsoft/TypeScript/pull/13921

**Comment by angelozerr** [comment]
typescript@next (2.6.0) support that and I have implemented it:

![autoimportdemo](https://user-images.githubusercontent.com/1932211/31767446-5fd124b4-b4cb-11e7-884f-fb324d7e687d.gif)

See https://github.com/angelozerr/typescript.java/wiki/New-and-Noteworthy-1.4.0#completion-with-auto-import
