### ISSUE TITLE
Collapse elements in editor

### ISSUE THREAD

**Issue by micaelgallego** [angelozerr/typescript.java#23]
Maybe imports can be collapsed automatically as JDT does for Java

**Comment by angelozerr** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=490423

**Comment by angelozerr** [comment]
Today code folding uses line indentation (like VSCode)  and not AST (like JDT). I don't know if it will be easy to fold "import", see https://github.com/angelozerr/typescript.java/blob/master/eclipse/jsdt/ts.eclipse.ide.jsdt.ui/src/ts/eclipse/ide/jsdt/internal/ui/editor/folding/IndentFoldingStrategy.java

**Comment by micaelgallego** [comment]
Maybe searching for the first and the last lines with "import" as the first keyword the import section can be detected.

**Comment by angelozerr** [comment]
Yes it's the idea.

**Comment by angelozerr** [comment]
Done

![](https://github.com/angelozerr/typescript.java/wiki/images/TypeScriptCodeFoldingImport.png)

See https://github.com/angelozerr/typescript.java/wiki/New-and-Noteworthy-1.1.0#import-folding

**Comment by micaelgallego** [comment]
Cool!
