### ISSUE TITLE
Some git operations on TS files fail because node.exe (started from TSLint) holds lock on files

### ISSUE THREAD

**Issue by stenzengel** [angelozerr/typescript.java#232]
Some git operations on TS files fail, because node.exe (started from TSLint) locks files. The error is reproducible at least on Windows computers:
- Create new TypeScript project with enabled TSLint (!) and a class (e.g. as discribed in the Wiki but you can use the embedded node, typescript and tslint: https://github.com/angelozerr/typescript.java/wiki/TypeScript-Wizards#project)
- Select the created project -> context menu -> Team -> Share project ...
- Select "Use or create repository or create new one"
- Select the project
- Create Repository
- Finish
- Commit all files (e.g. in "Git Staging" view)
- Modify created class and save
- Verify that there are TSLint warnings (i.e. there is an existing tslint.json and TSLint is working)
- Select the modified file -> context menu -> Replace with -> Head revision
- Confirm "Discard Changes"

An error occurs:
Checking out files failed
Checkout conflict with file: new_file.ts

When looking in the Windows Resource Monitor (https://superuser.com/questions/117902/find-out-which-process-is-locking-a-file-or-folder-in-windows), you can observe that node.exe holds a lock on the modified TS file.

My current workaround is to close all TS editors in Eclipse and restart Eclipse. Then the Git operations succeed.

Used versions:
- Eclipse: Oxygen.2 Release (4.7.2)
- TypeScript Eclipse IDE: 1.4.0.201708112157

**Comment by angelozerr** [comment]
@stenzengel don't use TSlint preferences which is not performant (I must remove that), but please use https://github.com/angelozerr/tslint-language-service which is a TypeScript plugin. It's more performant because it uses tsserver to validate files with tslint (no double parsing of files, just one node.exe process)

**Comment by stenzengel** [comment]
@angelozerr I thought, that I did already use tslint-language-service? Does the attached test project not use tslint-language-service? What do I have to do, to not use "TSlint preferences" but tslint-language-service?
[TypeScript2.zip](https://github.com/angelozerr/typescript.java/files/1639901/TypeScript2.zip)

What is the correct procedure to create a "linted" TypeScript project in Eclipse?

**Comment by angelozerr** [comment]
@stenzengel sorry I have read too quick your comment. Your project consumes tslint-language-service.

Have you the same problem without tslint?

**Comment by stenzengel** [comment]
@angelozerr When I delete the five lines for the tslint-language-service in tsconfig.json, the problem disappears. After adding the five lines again, the problems re-appears (The TS editor must be open and show some warnings). The problem is very reproducible, even without a restart of Eclipse. Can you reproduce the behaviour?

**Comment by stenzengel** [comment]
@angelozerr I have found a better workaround for the problem. It is faster than closing all editors and restarting Eclipse, especially if a launch configuration is running in Eclipse: 
- Remove the five lines for tslint-language-service in tsconfig.json
- Save
- Undo
- Save

But this workaround is still quite annoying and hinders the adoption of your (otherwise excellent) plug-in in our team. A bugfix would be very appreciated. Please tell me, if I can help.

**Comment by stenzengel** [comment]
The problem does not occur, if not the embedded typescript, tslint and tslint-language-service are used, but current versions of these packages are installed in the "New TypeScript Project" wizard.

Currently, these are the most recent versions. I do not have the lock problem when using these versions:
- typescript@2.6.2
- tslint@5.9.1
- tslint-language-service@0.9.8

@angelozerr The problem seems to be in an older version in one of those packages. If you embed new versions of these packages in your next release of your TypeScript-Plug-In, the problem will probably not appear anymore.

**Comment by angelozerr** [comment]
> @angelozerr The problem seems to be in an older version in one of those packages. If you embed new versions of these packages in your next release of your TypeScript-Plug-In, the problem will probably not appear anymore.

Thanks for this cool information. I must just find time to do that.

**Comment by stenzengel** [comment]
Closing because project is marked as outdated
