### ISSUE TITLE
support html-content-assist within template literal

### ISSUE THREAD

**Issue by nimo23** [angelozerr/typescript.java#234]
Please support 
- **content-assist** of html-elements 
- **validation of well-formed closing/ending-tags** of html-elements 
- **collapsing** of html-elements (tree-collapsing)
- **formatting** of html-elements (intentation)

**within es6-template literal of salsa editor (jsx-editor/typescript):**

For instance:

```
// es6 template literal starts with ` and ends with `
const myDiv = `
	<div class="list">
	<ul>..</ul>
	</div>
	`;
```

"myDiv" contains html-code. 

Actually it is not easy with the editor to check for well-formed starting/ending tag if "myDiv"-content is long. 

And content-assist for html-elements could be also supported like typical html-editor. 

So within a template literal, when **html-content is found, the editor should use typical html-editor-capabilities. Sounds simple, but I dont know, if this is possible.** 

With jsx we already have xml-like syntax, so maybe you can extend this to the html-content within template literals.

**Comment by angelozerr** [comment]
Please suggest this feature to TypeScript project. Those features are manages with tsserver.
