### ISSUE TITLE
Strange colors

### ISSUE THREAD

**Issue by huntering** [angelozerr/typescript.java#237]
Just installed Angular plugin 1.3.0. The coloring scheme looks awkward. The source code is all blue and not at all like the screenshots in https://github.com/angelozerr/typescript.java/wiki/Editor-Features.
![image](https://user-images.githubusercontent.com/5931517/38992174-32e0aba6-43e0-11e8-938b-60a8a87b90e6.png)

**Comment by pounard** [comment]
You can restore default Eclipse color, open Preferences, then go to "JavaScript > TypeScript > Editor > TextMate" - in this page uncheck the "Use TextMate for syntax coloring" checkbox. It took me a while to figure this one out !
