### ISSUE TITLE
Following deprecation, what plugin will show a menu on package.json?

### ISSUE THREAD

**Issue by tYYGH** [angelozerr/typescript.java#248]
Using Typescript IDE, I could “open” file `package.json`, and it would show the defined npm scripts (`start`, `serve`, `mock-server`… depending on what scripts are defined in `package.json`).

The deprecation notice says to use WWD, but that plugin does not have this feature. What plugin would you recommend to have this feature?

**Comment by angelozerr** [comment]
I suggest you that you create an issue in WWD in order to submit the idea to support this feature.

**Comment by tYYGH** [comment]
Ah. So this feature has been lost in the process… OK, I’ll create a issue in WWD.
Thank you angelozerr for your quick answer, and above all for all your great work!
