### ISSUE TITLE
Refresh project when creating duplicate file

### ISSUE THREAD

**Issue by micaelgallego** [angelozerr/typescript.java#25]
Now it is necessary to refresh explicitly to see new file

**Comment by angelozerr** [comment]
Sorry I don't understand?

**Comment by micaelgallego** [comment]
I've made an screen recording.

![anim](https://cloud.githubusercontent.com/assets/1072424/13728053/dc227146-e90a-11e5-8e65-24902081612d.gif)

I'm using default workspace settings, that is, "Refresh using native hooks or pooling" is not activated.

**Comment by angelozerr** [comment]
Could you retest it please since now we have a custom TypeScript editor.

**Comment by micaelgallego** [comment]
It works as expected now.
