### ISSUE TITLE
Compilation errors don't appear in Problems view

### ISSUE THREAD

**Issue by micaelgallego** [angelozerr/typescript.java#27]
Errors only appear in editor

**Comment by angelozerr** [comment]
@micaelgallego I have implemented this feature with WTP Validator. Please see https://github.com/angelozerr/typescript.java/wiki/Editor-Features#problem-view and tell me if it works for you.

Thanks.

**Comment by angelozerr** [comment]
@micaelgallego can I close this issue?

**Comment by micaelgallego** [comment]
Yes. But please, do what you have to do to enable this automatically. If WTP is not user friendly, implement validation with other technique.

**Comment by angelozerr** [comment]
@micaelgallego now I suggestion you DON'T use WTP TypeScript Validator, but I suggest you that you use "Compile/Build on save" feature. See https://github.com/angelozerr/typescript.java/wiki/TypeScript-Compiler#on-save

**Comment by micaelgallego** [comment]
+1
