### ISSUE TITLE
Ctrl+Shift+T is not working for finding types in TypeScript projects

### ISSUE THREAD

**Issue by micaelgallego** [angelozerr/typescript.java#29]
Maybe a new Keyboard short-cut it is necessary to avoid confusion between Java and TypeScript types.

**Comment by angelozerr** [comment]
To implement that, tsserver must provide a new command to retrieve hierarchy type:  https://github.com/Microsoft/TypeScript/issues/8268

**Comment by angelozerr** [comment]
It seems that PR https://github.com/Microsoft/TypeScript/pull/10482 should provide a new "implementation" command name for tsserver. Very cool!
