### ISSUE TITLE
Support for TypeScript compilation

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/typescript.java#3]

**Comment by angelozerr** [comment]
@piotrtomiak @micaelgallego  I have implemented "compile on save". See demo at:

![compilationonsavedemo](https://cloud.githubusercontent.com/assets/1932211/15249670/11eef722-1921-11e6-92f7-e1c2aea8af65.gif)

This demo use Eclipse Neon and extends WTP JSON Editor to have completion for tsconfig.json (liek "files", etc but only for the first level).

I have started to implement too "buildOnSave".

It exists too the capability to do Run As -> Compile TypeScript. I have started to write doc at https://github.com/angelozerr/typescript.java/wiki/TypeScript-Compiler

Any feedback are welcome!

**Comment by micaelgallego** [comment]
Really cool!! Plase keep doing this awesome work.
