### ISSUE TITLE
Autocompleting is not working in import path

### ISSUE THREAD

**Issue by micaelgallego** [angelozerr/typescript.java#31]
See https://github.com/Microsoft/TypeScript/issues/188

**Comment by angelozerr** [comment]
We must wait for that tsserver supports the issue that you have referenced.

**Comment by micaelgallego** [comment]
It seems it is scheduled for [TypeScript 2.0](https://github.com/Microsoft/TypeScript/milestones/TypeScript%202.0) as a lot of users are requesting it

**Comment by micaelgallego** [comment]
Issue related to this one: https://github.com/Microsoft/TypeScript/issues/188

**Comment by angelozerr** [comment]
TypeScript 1.2.0 embed now TypeScript 2.1.4 https://github.com/angelozerr/typescript.java/wiki/New-and-Noteworthy-1.2.0#typescript-214 which supports completion for path:

![](https://github.com/angelozerr/typescript.java/wiki/images/TypeScriptCompletionOnPath.png)

I close this issue.
