### ISSUE TITLE
Select only the name of the declaration when going to it from reference (Ctrl+Click)

### ISSUE THREAD

**Issue by micaelgallego** [angelozerr/typescript.java#32]
In JDT when going to declaration, only the name of the element is selected. In TypeScript.java, all class or method is selected. I think the behavior should be the similar to JDT.

**Comment by angelozerr** [comment]
It's tsserver which works like this. VSCode have the same behaviour.

**Comment by micaelgallego** [comment]
In cases like this, when tssserver behaves differently from JDT, do you plan to let tsserver default behavior or tweak it to be similar than JDT?

**Comment by angelozerr** [comment]
I don't want to tweak tsserver because this tsserver comes from the installed typescript that user can install it. I sugguest you that you create an issue at https://github.com/Microsoft/TypeScript/issues

**Comment by micaelgallego** [comment]
If you plan to use tsserver behavior when it is different than JDT, then you can close this issue.

**Comment by angelozerr** [comment]
I suggest you that you create an issue to TypeScript and you link it to this issue.

**Comment by micaelgallego** [comment]
I know, but the tsserver behavior is not anything that need to be fixed. It is only that eclipse uses other convention when goes to definition. For this reason maybe it has no sense to create an issue for TypeScript

**Comment by angelozerr** [comment]
As I said you, I don't want to tweak tsserver.

**Comment by micaelgallego** [comment]
Your opinion is ok for me. You can close this issue then.

**Comment by angelozerr** [comment]
Ok.
