### ISSUE TITLE
TypeScript editor is referred as "JavaScript editor" when open a file

### ISSUE THREAD

**Issue by micaelgallego** [angelozerr/typescript.java#35]

**Comment by angelozerr** [comment]
what do you mean? Please provide a screenshot. Thanks!

**Comment by micaelgallego** [comment]
Here is:

![image](https://cloud.githubusercontent.com/assets/1072424/14048617/ba84b84c-f2af-11e5-8ebb-a9ad20c1989b.png)

TypeScript editor is referred as JavaScript editor. It is not important, but confusing.

**Comment by angelozerr** [comment]
Since https://github.com/angelozerr/typescript.java/issues/41 now we have Open With -> TypeScript Editor.
