### ISSUE TITLE
Improve method auto-completion writing parameter names

### ISSUE THREAD

**Issue by micaelgallego** [angelozerr/typescript.java#37]
In JDT when you select a method from autocomplete list, parenthesis are written to code, and the parameter names (from documentation or source code) are written also. The parameters are also selected to edit them. Moreover, in methods with several parameters, every parameter is boxed and developer can navigate with tab key between them. I think TypeScript should have the same behavior. For now, only the method name is written to the file.

**Comment by angelozerr** [comment]
Indeed, I had this idea. I have already done that inside tern.java

**Comment by angelozerr** [comment]
This feature is done. It works like JDT Recommenders: the completion items which are shown, matche prefix with "longest continuous sequence" (and not with starts with) like JDT does. If you have Neon, you will have highlight. Here a demo:

![typescriptcompletiondemo](https://cloud.githubusercontent.com/assets/1932211/15359406/725f0552-1d09-11e6-9fdd-6e66af28922d.gif)

@micaelgallego  @piotrtomiak  do you think we must have a preference to choose completion wich works with "starts with"?

**Comment by micaelgallego** [comment]
Awesome work ;)...

But I prefer to stay as close to JDT as possible to reduce the [uncanny valley](https://en.wikipedia.org/wiki/Uncanny_valley) when working with Java and TypeScript in the same project.

**Comment by angelozerr** [comment]
> But I prefer to stay as close to JDT 

You mean that it is OK. If yes can I close this issue?

**Comment by micaelgallego** [comment]
I think it would be good to have a preference to choose between this behavior and "starts with" behavior.

But it is up to you ;)

**Comment by angelozerr** [comment]
> I think it would be good to have a preference to choose between this behavior and "starts with" behavior.

Ok but this behaviour is now with JDT Eclipse Neon

**Comment by micaelgallego** [comment]
Ahhh... I didn't understand you sorry ;)

Then close the issue ;)
