### ISSUE TITLE
Outline is missing for TypeScript files

### ISSUE THREAD

**Issue by micaelgallego** [angelozerr/typescript.java#38]

**Comment by angelozerr** [comment]
This feature must be implmented with tsserver navbar.

But as outline can be overrided https://bugs.eclipse.org/bugs/show_bug.cgi?id=490426 I will create for the moment a new view "TypeScript Outline"

**Comment by micaelgallego** [comment]
TypeScript editor is a brand new editor that doesn't depend on JSDT but outline is still missing.

**Comment by angelozerr** [comment]
Yes I must implement it by using tsserver command (I think it exists one for tha.t)

**Comment by angelozerr** [comment]
Done

![](https://github.com/angelozerr/typescript.java/wiki/images/TypeScriptOutline.png)

See https://github.com/angelozerr/typescript.java/wiki/Editor-Features#outline-view

**Comment by danielvanmil** [comment]
The standard JSDT/java outline has some more features like sorting/collapse-expand/filter private-public etc, It would be nice to at least have a collapse/expand as TS files can get huge because of the fact that lots of people implement a lot of types in one TS file. Any plans?

**Comment by angelozerr** [comment]
@danielvanmil please create an issue per features please. I think collapse/expand is not hard to implement.

**Comment by angelozerr** [comment]
@danielvanmil see https://github.com/angelozerr/typescript.java/issues/78 I'm working on that. For filter I don't know if I will implement it (I prefer implementing other features like template snippets)

**Comment by angelozerr** [comment]
@danielvanmil TypeScript Outline was a lot improved (Collapse All, Link With Editor, Keep selection when outline is refreshed, etc). See https://github.com/angelozerr/typescript.java/wiki/New-and-Noteworthy-1.1.0#typescript-outline

You can install 1.1.0-SNAPSHOT to test it.
