### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/typescript.java#39]
I would like to create a release for typescript.java. Before doing that I would like to know @micaelgallego  @piotrtomiak which important features must be implemented for this release.

Today we have
 * for editor completion, hover, validation, hyperlink for typescript files. 
 * User can specify the version of TypeScript with preferences.

IMHO I think tsc (typescript compiler) must be implemented (I have started it, but it's not very robust).

If you think that there are other important features, tell me and I will develop it before doing the release. 

Many thanks @micaelgallego  @piotrtomiak for your feedack!

**Comment by micaelgallego** [comment]
Thank you for asking to us @angelozerr ;)

I think TSC is an importante feature, but I think that your plugin can be released without it. I think there are use cases where other tool is responsible of compilation. For example, in the angular 2 seed projects, there are gulp or webpack tasks in charge of this, with file watchers and autoreload. For that, and in the spirit of "release often, release early", for me it is ok to release the first version of typescript.java without TSC.

My 2 cents ;)

**Comment by angelozerr** [comment]
Done, thank you @pascalleclercq !
