### ISSUE TITLE
TypeScript editor not found

### ISSUE THREAD

**Issue by micaelgallego** [angelozerr/typescript.java#43]
In master version (commit 1dcb95c63fbc712920ab1a1f28433bb1687b0bd1) There is no TypeScript editor available. Files with .ts extension are opened with Text Editor. 

If I try to open with other editor, TypeScript editor is not found. 

![image](https://cloud.githubusercontent.com/assets/1072424/14362095/59ab9884-fcfe-11e5-82ac-51449d2b0a1d.png)

**Comment by angelozerr** [comment]
You need for the moment to import new project ts.eclipse.ide.ui.editor that I will merge with jsdt project

**Comment by angelozerr** [comment]
@micaelgallego please resynchronize you.

**Comment by micaelgallego** [comment]
Ups... eclipse didn't show me any error and I had missed to look if there were new projects.

I've imported new projects but now I have the following errors:
* Bundle 'org.eclipse.json' cannot be resolved
* Bundle 'org.eclipse.wst.json.core' cannot be resolved
* Bundle 'org.eclipse.wst.json.ui' cannot be resolved

How can fix these errors?

Thanks in advance.

**Comment by angelozerr** [comment]
Don't import thoses JSON plugins https://github.com/angelozerr/typescript.java/tree/master/eclipse/json for the moment. They are based on Eclipse WTP JSON Editor which will be available for Eclipse Neon.

**Comment by micaelgallego** [comment]
Then Can I ignore these errors?

**Comment by angelozerr** [comment]
Yes, you can ignore those errors.

**Comment by micaelgallego** [comment]
Thanks. Then maybe will be better to close this issue as is not really an issue.
