### ISSUE TITLE
Editor for source map *.js.map

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/typescript.java#48]
Today when we try to open a source map *.js.map file, Eclipse tries to open it with system editor (In my case I have VSCode installed, and it opens VSCode).

Source map follow JSON syntax. It should be good to link *.js.map file to the Neon JSON Editor. 

@piotrtomiak are you OK with that?

**Comment by piotrtomiak** [comment]
Sounds good, but I hope the editor is able to wrap lines and handle large files. Some map files are really huge. Besides, users are not expected to edit those files anyway.

**Comment by angelozerr** [comment]
> Sounds good, but I hope the editor is able to wrap lines and handle large files. Some map files are really huge. 

Very good answer! Indeed there is a problem with JSON Editor with large file. See
https://bugs.eclipse.org/bugs/show_bug.cgi?id=487906

So not sure it's a good idea to do this issue.

**Comment by angelozerr** [comment]
I close this issue, since JSON Editor cannot support large file.
