### ISSUE TITLE
Display TypeScript Elements in the Project Explorer

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/typescript.java#53]
Display TypeScript Elements in the Project Explorer by using build path folders.

**Comment by angelozerr** [comment]
Here a screenshot about my idea:

![typescriptresources](https://cloud.githubusercontent.com/assets/1932211/14895350/77384d0e-0d78-11e6-93dc-5fdf5766b52a.png)

You can see that there is a "TypeScript Resources" node which displays the src folder because it contains tsconfig.json. 

The tsconfig.json is searched inside root project and src folder for the moment. After you will able to add other folders.

Those folders (called build path) are used for validation and compilation (soon finished).

After my idea is to displays ts files inside those folders.

@piotrtomiak @micaelgallego please give me feedbacks.

**Comment by angelozerr** [comment]
@piotrtomiak @micaelgallego please read https://github.com/angelozerr/typescript.java/wiki/TypeScript-BuildPath#what-is-build-path

Here a demo:

![](https://github.com/angelozerr/typescript.java/wiki/images/DemoWithBuildPath.gif)

**Comment by micaelgallego** [comment]
I like this behavior ;) Good job.

How do you plan to manage "node_modules" folder? Do you plan to create an special element in project folder like Java's "Maven dependencies" or similar?

**Comment by angelozerr** [comment]
> I like this behavior ;) Good job.

Thanks!

> How do you plan to manage "node_modules" folder? 

What do you mean with that? Exclude "node_modules" folder for validation, compilation? If it that you can exclude "node_modules" with tsconfig.json. 

So now when a full validation is done, it uses build path folders to know if validation must be done or not. So for instance if you have

 * src
 * node_modules

And your build path is src, node_modules is not validated.

if you have

 * src
  * node_modules

In this case your src/tsconfig.json must declare "node_modules" inside "exclude" JSON array.

**Comment by micaelgallego** [comment]
It looks good to me. Thanks
