### ISSUE TITLE
Contribute TypeScript project detection to Smart Importer

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/typescript.java#54]
Smart Importer is a very cool features to import project and discover while importing some files to add directly the well nature, etc

Today I have not TypeScript nature, but I think more and more we should have this TypeScript nature to hide for instance TypeScript from Project properties.

It should be cool when we import a project 

 * it check that it exists a tsconfig.json or a ts files and add TypeScript nature to the project.
 * the buildpath is updated with directory folder which contains tsconfig.json

See sample with JPA at https://bugs.eclipse.org/bugs/show_bug.cgi?id=492323

@mickaelistria could you give me more information about "Smart Importer":

 * if I have understood, it will work only with Neon?
 * can I download none release of Neon to benefit with Smart Importer?
 * if each project uses RecursiveFileFinder to discover a file, is not a problem with performance? If we have JPA and TypeScript which provides smart importer, it means that files of project is visited twice?

**Comment by mickaelistria** [comment]
I would recommend that as much as you can avoid a nature, do it. Natures introduce a lot of complexity both from maintenance and usage perspective.

About the Smart Importer, Neon M6 has it. However, the API is subject to change. Using the recursiveFileFinder can cause performance issue.

**Comment by angelozerr** [comment]
> I would recommend that as much as you can avoid a nature, do it. 

Many thanks for your recommandation! Today there are none nature. I use tsconfig.json to know if project is a typescript project or not. See my current work at https://github.com/angelozerr/typescript.java/issues/53#issuecomment-215505900

**Comment by angelozerr** [comment]
@mickaelistria see https://github.com/angelozerr/typescript.java/wiki/TypeScript-BuildPath#typescript-nature if you are interested to know the rules how I manage "TypeScript Nature" without "Eclipse Nature".
