### ISSUE TITLE
tsconfig.json editor like PDE

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/typescript.java#57]
See http://stackoverflow.com/questions/31750964/typescript-compile-on-save-feature-not-working-in-visual-studio-2015 to add UI config

![](http://i.stack.imgur.com/QSWMo.png)

**Comment by angelozerr** [comment]
@piotrtomiak I have read https://www.genuitec.com/myeclipse-twitter-chat-recap-august-30th/ and I tell me if you are using typescript.java or your own solution?  If you don't use typescript.java, I will stop to spam you.

If you are using typescript.java (I hope so:)) I have seen you provide an UI preferences for tsconfig.json. IMHO I think it's not very user friendly since a project can have several tsconfig.json. I think it's better to have a tsconfig.json editor like PDE with several tabs. What do you think about that?

**Comment by piotrtomiak** [comment]
@angelozerr - it was a tough decision, but we've decided to go with Palantir plugin, sorry...

As far as multiple tsconfig.json files are concerned, you are right and we will be providing both ways, I think.

**Comment by atsu85** [comment]
@piotrtomiak, I'm wondering what were the reasons. I guess @angelozerr would also be very interested in knowing what is missing from this plugin or what features are better implemented in Plantir plugin. 

Please share the reasons You did the decision!

**Comment by angelozerr** [comment]
> it was a tough decision, but we've decided to go with Palantir plugin, sorry...

It's really shame for me -( I like to work with you like we have done with tern.java. Many thank's for your answer and good luck for your support!

> Please share the reasons You did the decision!

@piotrtomiak when you will have time, I'm very interested why you have done this decision. Thanks!

**Comment by angelozerr** [comment]
@atsu85 is it possible for you to help me to design the tsconfig editor. There are many options http://json.schemastore.org/tsconfig and I would like to create several section like General, Output, etc

Many thank's for your help!

**Comment by angelozerr** [comment]
@atsu85 @micaelgallego I have implemented my idea about managing tsconfig.json with UI by splitting options in several pages (it's not finished but it starts working).

 * `Overview` page
 
![Overview page](https://github.com/angelozerr/typescript.java/wiki/images/TSConfigEditorOverviewPage.png)
 
 * `Files` page
 
![Files page](https://github.com/angelozerr/typescript.java/wiki/images/TSConfigEditorFilesPage.png)

 * `Output` page
 
![Output page](https://github.com/angelozerr/typescript.java/wiki/images/TSConfigEditorOutputPage.png)

 * `Source` page
 
![Source page](https://github.com/angelozerr/typescript.java/wiki/images/TSConfigEditorSourcePage.png)

See https://github.com/angelozerr/typescript.java/wiki/New-and-Noteworthy-1.1.0#tsconfig-editor for more information

Please give me feedback (perhaps I have missed some options, are you OK to organize those options in several pages, are you OK with name of each section (JSX, Reporting, Files, etc)

Many thanks for your help!

**Comment by atsu85** [comment]
@angelozerr, fantastic work! I have to say, that I've been using IDEA for more than month (and I've committed myself to it by buying the Ultimate license).

However there is one suggestion that might be worth considering. Perhaps it makes sense to group type-safety (or strong typing) related flags to separate section. Most notably following flags: noEmitOnError, noImplicitAny, strictNullChecks.

I wish You had started the work on this plugin 2 years ago, looks like this plugin is moving to the right direction. 
Also I've noticed, that You are building smth for Angular2 - I hope You don't commit Yourself too much to it (I've been using [Aurelia](http://aurelia.io/) in production even before it reached alpha, and I like it much more than Angular2) ;)

**Comment by hdave** [comment]
This is great stuff....good work!

**Comment by angelozerr** [comment]
@atsu85 could you give me a detailled answer please (section name, which fields are hosted in teh X section, etc)

Thanks!

**Comment by angelozerr** [comment]
@atsu85 have you te intention to use typescript.jav aor continue to use WebStorm?

I would like to have a lot of feedbacks and perhaps we could work together to implement eclipse plugin for aurelia based on typescript.java? What do you think about that?

**Comment by atsu85** [comment]
@angelozerr 
> could you give me a detailled answer please (section name, which fields are hosted in teh X section, etc)

Yes, I think You have managed to group the flags very well, but since You asked my opinion, I'd say that
> following flags: noEmitOnError, noImplicitAny, strictNullChecks.

and perhaps `noImplicitReturns` are all related to stronger typing or safety (but I don't have very good name for them right now). Clearly `noEmitOnError` is also related to "Output" section where it is right now and `noImplicitAny`, `strictNullChecks` are related to validation where they are right now. However it seems to me, that these flags are one of the most useful/influential flags if You want to prevent shooting Yourself into the foot, so they might deserve a special section or perhaps a bit more prominent location in their current section.

Also You might consider having separate section related to experimental features, most notably decorators (`experimentalDecorators` and `emitDecoratorMetadata` used by Angular2 and Aurelia).

Once again, fantastic work with this plugin!

**Comment by atsu85** [comment]
@angelozerr 
> @atsu85 have you te intention to use typescript.jav aor continue to use WebStorm?

Right now I'm using IntelliJ Idea for full stack (including Java and tools related to it, not WebStorm, that is a subset merely meant for web development). Idea also has a primitive Aurelia plugin, but as Aurelia has much less boilerplate code, then the lack of some nice-to-have features are not so big deal for me. 
> perhaps we could work together to implement eclipse plugin for aurelia based on typescript.java?

I have to admit that I had some thoughts regarding trying to build one myself when I used Eclipse. It certainly seems that this project would be the best fit for Aurelia plugin, but now that I'm using IDEA, I'm not thinking about it any more. However I think that Angular2 plugin with this plugin would be quite easy to customize for Aurelia as well (as they are quite similar in a way with relatively small differences for the plugin and all the related tooling is also similar).

**Comment by angelozerr** [comment]
> but now that I'm using IDEA

That's very shame for me -( But I understand. Ok I will stop to spam you. Anyway thank's for your suggestions.!
