### ISSUE TITLE
tsconfig editor not working as documented

### ISSUE THREAD

**Issue by atsu85** [angelozerr/typescript.java#59]
# Setup
I have installed all the items (including "JSON Editors") to Eclipse Neon from the update site of this plugin:
http://img.iglu.ee/public/badce4b8-36ec-416b-9a79-1be564447034.png
as [documented](https://github.com/angelozerr/typescript.java/wiki/TSConfig-Editor-Features#typescript-config-editor) in wiki

# Problem
I get wrong autocomplete suggestions (ones for top-level elements, not for compilerOptions):
http://img.iglu.ee/public/b8dcd549-cc58-4ede-ae0a-ee28cdca4668.png

# Expected
Proposals in compilerOptions elements should work as documented:
https://github.com/angelozerr/typescript.java/wiki/TSConfig-Editor-Features#completion

Eclipse: Version: Neon Release Candidate 1 (4.6.0RC1) Build id: 20160519-1933

**Comment by angelozerr** [comment]
It's normal, this bug comes from Eclipse WTP JSON Editor which was fixed today https://bugs.eclipse.org/bugs/show_bug.cgi?id=490639

In my case I use source of Eclipse Neon to do the tsconfig.json editor screenshot. You must be patient and wait for a new build of neon
