### ISSUE TITLE
UI preferences for tsserver

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/typescript.java#6]

**Comment by atsu85** [comment]
Do I understand correctly, that this feature is already implemented:
https://github.com/angelozerr/typescript.java/wiki/Configuration#server
or is there smth You'd like to improve?

**Comment by angelozerr** [comment]
> Do I understand correctly, that this feature is already implemented:

Yes it's implemented. The only thing which must be done is validation when user select their own typescript bundle to check that it exists.

**Comment by angelozerr** [comment]
This issue is done, for validation see new issue https://github.com/angelozerr/typescript.java/issues/69
