### ISSUE TITLE
TypeScript editor doesn't work on Mac and on Windows

### ISSUE THREAD

**Issue by Mimetis** [angelozerr/typescript.java#61]
Hi,

I install your great typescript module for Eclipse Neon on a Windows Machine and on a MacBook machine.
And, on both machine, the typescript editor doesn't seems to work.

![a](https://cloud.githubusercontent.com/assets/4592555/15691560/14e98d00-2779-11e6-830f-3f9ab51455a3.png)

![b](https://cloud.githubusercontent.com/assets/4592555/15691561/14eaf97e-2779-11e6-81a9-11096b26a3b2.png)

**Comment by Mimetis** [comment]
and btw the indentation seems to be broken too :)

**Comment by angelozerr** [comment]
> And, on both machine, the typescript editor doesn't seems to work.

What do you mean? You speak about completion which doesn't work? If you do Ctrl+space, the completion doesn't work? Perhaps you wish that completion opens when you type '.'

If it that you must activae preferences (Window/Preferences) like this:

![enableautoactivation](https://cloud.githubusercontent.com/assets/1932211/15707303/4f7abcbc-27f8-11e6-92bc-d83701f947d6.png)

> and btw the indentation seems to be broken too :)

Yes I know see https://github.com/angelozerr/typescript.java/issues/58 and I'm working for the moment to try to support .editorconfig with https://github.com/ncjones/editorconfig-eclipse/ inside TypeScript Editor.

**Comment by Mimetis** [comment]
Yes I have tried to activate this option, but it seems it doesn't work. I tried either typing a "." or "Ctrl-Space", no one works.

Here screenshots on a .js file that is actually working as expected.
<img width="340" alt="js" src="https://cloud.githubusercontent.com/assets/4592555/15708412/ba6749d6-27fe-11e6-8993-5cb83562044b.PNG">

In a .ts file, Nothing appears :(

<img width="250" alt="ts" src="https://cloud.githubusercontent.com/assets/4592555/15708505/1ca141ce-27ff-11e6-99f0-8dc291ec1156.PNG">

I can send you a remote access to my VM. It's a Win Server 2012 with VS Community and Eclipse Neon installed if you're interested :)

Next week, I made a presentation of TypeScript at EclipseCon in France, I hope to make a demo with typescript.java plugin ! Hope we will find together where is the problem (IMO it could be a mistake from me :) )

**Comment by angelozerr** [comment]
Could you share your project please?

**Comment by Mimetis** [comment]
There is no errors logged.

I sent you on your @gmail a remote connection to my VM. I think it will be more simple to debug for you :)

**Comment by Mimetis** [comment]
Ok, thx angelozerr, bug resolved ! Issue closed

**Comment by angelozerr** [comment]
You are welcome @Mimetis. It was just a problem with the build which was not done.
