### ISSUE TITLE
add fileExtension_ts to Marketplace entry

### ISSUE THREAD

**Issue by atsu85** [angelozerr/typescript.java#62]
I'm quoting @mickaelistria from [palantir/eclipse-typescript](https://github.com/palantir/eclipse-typescript/issues/321) project:
> Eclipse Marketplace and Marketplace client in IDE recently added support for discovery of marketplace extensions for a given filetype. In order to get this plugin discovered by users opening *.ts files, it seems important to add the fileExtension_ts tag to the marketplace entry.

**Comment by angelozerr** [comment]
Yes @atsu85 I will do that once typescript.java will be released.

**Comment by angelozerr** [comment]
Done at https://marketplace.eclipse.org/content/typescript-ide (must just wait for accept of moderator).
