### ISSUE TITLE
Use Java8

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/typescript.java#63]
I would like to use https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html (which requires Java8) instead of using collector (seehttps://github.com/angelozerr/typescript.java/blob/master/core/ts.core/src/ts/client/TypeScriptServiceClient.java#L169)

It means that Java8 is required. Since Neon requires Java8, I think we can have Java8 depdendency.

@piotrtomiak are you OK with that?

**Comment by piotrtomiak** [comment]
@angelozerr - sure

**Comment by hdave** [comment]
Yes - not a problem.

**Comment by cm325** [comment]
Great to hear, so does this mean this plugin works now with java 8 on eclipse neon?

**Comment by angelozerr** [comment]
@cm325 typescript.java 1.0.0 (and perhaps 1.1.0) is based on Java6 and  not linked to Neon (just for tsconfig.json editor)

But I would like to use Java8 CompletableFuture. I have created this issue to know if use of Neon + Java8 is OK for typescript.java users.

**Comment by cm325** [comment]
Ok... so, can I install this on Neon and will it work if eclipse is setup
to use a java 8 jdk?

**Comment by angelozerr** [comment]
typescript.java works with Neon. If you wish to use Neon you will need Java8.

**Comment by cm325** [comment]
great, thanks!

**Comment by angelozerr** [comment]
@boniatillo-com just for your information, now I have a clean API with Java8 CompletableFuture. See https://github.com/angelozerr/typescript.java/blob/master/core/ts.core/src/ts/client/ITypeScriptServiceClient.java
