### ISSUE TITLE
Wrong generated brace after Enter

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/typescript.java#72]
If we have this contant:

```
class A {// here we typer Enter
  f() {
  }
}
```

Enter generates a wrong brace:

```
class A {

} // here wrong brace is generated
  f() {
  }
}
```

The JSDT editor does like this.

**Comment by angelozerr** [comment]
It's a JSDT issue. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=500465

**Comment by sdargutev** [comment]
This seems to be a conflict between the Preference "Window->Preferences->JavaScript->Editor->Typing--> 'Automatically close {Braces}'", and maybe own implementation of inserting matching brace?

If you remove the checkmark from the 'Automatically close {Braces}' preference, the editor does not insert unneeded brace anymore, and it all works fine.

**Comment by angelozerr** [comment]
@sdargutev I'm using JSDT code to manage insert of bracket. There is the same problem with JSDT JavaScript Editor. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=500465
