### ISSUE TITLE
Requesting support for type declarations installed using npm @types

### ISSUE THREAD

**Issue by jalbr74** [angelozerr/typescript.java#74]
I was trying out the new webpack version of angular-cli, and discovered how easy it was to install third party libraries, and import them in my code.

For example, to install the 3rd party library "abs", I only had to do the following:

Create a new angular2 project:
`$ ng new my-app`

Install a 3rd party library, such as "abs":
`$ npm install abs --save`

Install the TypeScript definitions by doing the following:
`$ npm install @types/abs --save-dev`
(see: https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/)

Then from any of my components, I'm able to import it as follows:
`import abs from 'abs';`

However, the problem I'm seeing is my Eclipse gives me the message: "Cannot find module 'abs'."

I'm assuming this is because the Eclipse plugin doesn't yet recognize the new way of installing and importing 3rd party libraries using "@types".  I'm a Java developer trying to learn angular2, so I'm not sure exactly how it works, but when I open the project in WebStorm, I don't get the same error.

Since I'd much rather use Eclipse with your plugin, I thought I'd post a feature request here so Eclipse could recognize this method of managing 3rd party libraries as well.

Thanks for all the great work!

**Comment by angelozerr** [comment]
> I was trying out the new webpack version of angular-cli, and discovered how easy it was to install third party libraries, and import them in my code.

Please try [Angular2 Eclipse](https://github.com/angelozerr/angular2-eclipse/wiki/Getting-Started) which provides [AngularCLI support with wizards, launches and terminal](https://github.com/angelozerr/angular2-eclipse/wiki/AngularCLI).

>  I'm assuming this is because the Eclipse plugin doesn't yet recognize the new way of installing and importing 3rd party libraries using "@types".

I'm not sure but I think @types come from with TypeScript 2.0. typescript.java provides TypeScript 1.8.10 by default, but you can use your own TypeScritp version:

 * create you a project and do "npm innstall typescript@next"
 * go at Server project preferences and select "${project_loc:node_modules/typescript}" in the installed TypeScript to use typescript 2.0.0

**Comment by jalbr74** [comment]
Thanks for the reply.  You're absolutely right, when I set my Installed TypeScript setting to: "${project_loc:node_modules/typescript}", the problem went away.  Thanks for the suggestion!

I'll give Angular2 Eclipse a try, as well.  Thanks!

**Comment by angelozerr** [comment]
Glad it works for you and hope you will liek Angular2 Eclipse.
