### ISSUE TITLE
Typescript Core package can't be installed into Eclipse (with Luna?)

### ISSUE THREAD

**Issue by alexeiych** [angelozerr/typescript.java#75]
Hi,

I tried to install both 1.0.0 and 1.1.0 versions of Typescript IDE into my Eclipse Luna but Typescript Core package could not be installed for some reason. Am I missing anything from the installation process?
![image](https://cloud.githubusercontent.com/assets/21088693/17976093/fb430960-6ab9-11e6-9a4f-6b517858123f.png)

**Comment by angelozerr** [comment]
That's strange? I suggest you that you try with Eclise Jee Neon. You will benefit with JSON editor.

**Comment by alexeiych** [comment]
I work in controlled environment and it's not that easy to upgrade to Neon. Can you try to install your plugin on Luna and see if you get the same message please?

**Comment by atsu85** [comment]
@alexeiych, You could try it Yourself on Your personal computer with clean install and report the result back to @angelozerr - I'm sure he is super buzy writing new features ;)

**Comment by angelozerr** [comment]
As @atsu85 said, I'm developping typescript.java in my spare time, so I cannot take time to support several versions of Eclipse (I think it's your problem).

Luna is very old (2 years). I have started to develop typescript.java with Mars, so I think it should work, but not tested. Neon should be used with typescript.java and I hope Neon 2 will provide sourcemap debugging https://bugs.eclipse.org/bugs/show_bug.cgi?id=487465 to provide debugging for TypeScript https://github.com/angelozerr/typescript.java/issues/2

Hope you will understand that I cannot support Luna and Mars today.

**Comment by angelozerr** [comment]
None answer, I close this issue.
