### ISSUE TITLE
JSX Editor

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/typescript.java#77]
Today ts, tsx, jsx have ts icons. Provide an editor for JSX.

**Comment by angelozerr** [comment]
Done.

![](https://github.com/angelozerr/typescript.java/wiki/images/JSXEditor.png)

See https://github.com/angelozerr/typescript.java/wiki/JSX-Editor-Features

**Comment by rulatir** [comment]
I need this very badly and urgently! Can I somehow install 1.1 today, e.g. a nightly build or something?

**Comment by angelozerr** [comment]
@rulatir you can install 1.1.0-SNAPSHOT with update site. See https://github.com/angelozerr/typescript.java/wiki/Installation-Update-Site
