### ISSUE TITLE
Embedded node.js & Preferences

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/typescript.java#8]
Provides: 

 * Embedded node.js
 * a preferences to select the node.js to use (embedded or installed).

**Comment by atsu85** [comment]
Do I understand correctly, that this feature is already implemented:
https://github.com/angelozerr/typescript.java/wiki/Configuration#configure-nodejs

**Comment by angelozerr** [comment]
Like https://github.com/angelozerr/typescript.java/issues/6, the only thing which must be implemented is validation.

**Comment by angelozerr** [comment]
This issue is done, for validation see new issue https://github.com/angelozerr/typescript.java/issues/68
