### ISSUE TITLE
format on save

### ISSUE THREAD

**Issue by sdargutev** [angelozerr/typescript.java#81]
The format on save action seems to not work... However, ctrl+shift+f works. Would be nice to have the same functionality automatically on save.

**Comment by angelozerr** [comment]
> The format on save action seems to not work...

Indeed, it's not implemented. 

> Would be nice to have the same functionality automatically on save.

Yes sure, I must just find time to implement it.

**Comment by chance-lang** [comment]
+1 looking for this feature.

Plugin does a great job of formatting the JSX, now it just needs the Save Action to enforce it. Keep up the good work :)

PS. No idea the overhead/pain involved with getting some of the newer versions in the Eclipse Marketplace (1.0.0 is the latest) but that would be great too!

**Comment by angelozerr** [comment]
> Plugin does a great job of formatting the JSX, now it just needs the Save Action to enforce it.

Just find time to do that, I'm very busy with tslint integration for the moment.

> 1.0.0 is the latest

No it's 1.1.0. I think I will release 1.2.0 this month once I will integrate tslint + angular2 language service.

**Comment by boniatillo-com** [comment]
+1 to have a the 1.2.0 release this month :)

**Comment by angelozerr** [comment]
@boniatillo-com yes it's my goal:) I must just finish before tslint integration and angular-cli.
