### ISSUE TITLE
Embed TypeScript 2.0.3

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/typescript.java#88]
Add TypeScript 2.0.3 ad embed https://github.com/Microsoft/TypeScript/releases/tag/v2.0.3

**Comment by angelozerr** [comment]
Done:

![](https://github.com/angelozerr/typescript.java/wiki/images/UseTypeScript2AsServer.png)

See https://github.com/angelozerr/typescript.java/wiki/New-and-Noteworthy-1.1.0#typescript-203 for more information.

**Comment by micaelgallego** [comment]
Kudos!! You are awesome!! ;)

**Comment by angelozerr** [comment]
@micaelgallego glad you like this idea:)
