### ISSUE TITLE
Duplicate errors

### ISSUE THREAD

**Issue by hdave** [angelozerr/typescript.java#89]
I can replicate this with the ng2 tour of heros source code.  Essentially, I get an error in hero.service.ts.  Everytime I edit a related file and save (build on save is true), the errors for hero.service.ts are doubled.  Then tripled, etc. 

Here is a screenshot of what is happening.  Should I open a separate issue on why the error was there in the first place?  The code runs perfect and compiles from the command line without error.  I have the plugin configured to use my external npm (6.x) and typescript (2.0.3)

![ts errors](https://cloud.githubusercontent.com/assets/1245605/18842840/66a231b6-83e4-11e6-86be-84aac764cebd.PNG)

**Comment by angelozerr** [comment]
Let me try your sample. For the moment I have none idea why you have this problem.

**Comment by hdave** [comment]
I don't have a way to share my project, but you can get the exact same code here:

https://github.com/johnpapa/angular2-tour-of-heroes

**Comment by angelozerr** [comment]
@hdave I cannot reproduce your problem -(

* I have imported https://github.com/johnpapa/angular2-tour-of-heroes
* I have enabled TypeScript Builder
* I have added buildOnSave: true inside tsconfig.json
 * I open hero.service.ts. 
* I add a space, I save,  I add a space, I save, etc and it works well.

The only problem that I see is if you run the lauch "Compile" and you save your file just after. There are some problems sometimes (I will try to discover this problem).

**Comment by angelozerr** [comment]
@hdave please answer me to my question in order to I investigate to your problem. Thanks!

**Comment by Springrbua** [comment]
@angelozerr the problem is probably the same as in #132 ...  
As this one is opened since a very long time and a lot of things changed since then, I guess this one can be closed?

**Comment by angelozerr** [comment]
Yes sure @Springrbua 

@hdave if you have again the problem, please reopen it. Thanks.
