### ISSUE TITLE
UI preferences for tsc

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/typescript.java#9]

**Comment by atsu85** [comment]
I'm wondering if this is a subset of [#57 - tsconfig.json editor like PDE](https://github.com/angelozerr/typescript.java/issues/57) or is smth else meant here?

**Comment by angelozerr** [comment]
This issue is implemented https://github.com/angelozerr/typescript.java/wiki/Configuration#compiler the only thing to do is validation.

**Comment by angelozerr** [comment]
This issue is done, for validation see new issue https://github.com/angelozerr/typescript.java/issues/69
