### ISSUE TITLE
npm launch configuration?

### ISSUE THREAD

**Issue by hdave** [angelozerr/typescript.java#90]
I'm new to this plugin, so I am not sure if I misunderstand.  I see the Grunt, Gulp, TS Compile, and Nodejs run configurations.  But I would have thought there would be an "npm" run configuration.  Webstorm has this feature.  I could configure my own external tool run configuration, but is there a better way to run my npm scripts?

**Comment by angelozerr** [comment]
npm, grunt is managed by Eclipse Jee Neon not by typescript.java. I think https://bugs.eclipse.org/bugs/show_bug.cgi?id=491474 should fix your wish, but you must wait next release of Eclipse Jee Neon.

**Comment by hdave** [comment]
I did not know that!  I thought that was your magic....thanks I will await it in Neon.

**Comment by angelozerr** [comment]
Perhaps you want just update your package.json to download your angular and co dependencies? If it that you can open contenual menu after selecting package.json and do "Run As -> npm Update"
