### ISSUE TITLE
No Preferences on Eclipse Neon

### ISSUE THREAD

**Issue by Rhobal** [angelozerr/typescript.java#91]
I installed typescript.ide, both 1.1.0-Snapshot and 1.0.0, on Eclipse Neon and never see a "TypeScript" preferences entry in project or global preferences.
I even tried installing Neon on a (Win 10) PC that had never seen eclipse before; same effect.

I do get Typescript editor and validator, which complains that every single identifier is a duplicate, although Ctrl-Shift-G doesn't find a second instance.

**Comment by angelozerr** [comment]
> and never see a "TypeScript" preferences entry in project 

If you have a tsconfig.json inside your project or inside src, you should see it. Please read https://github.com/angelozerr/typescript.java/wiki/TypeScript-BuildPath#typescript-nature

> or global preferences.

You have not JavaScript / TypeScript preferences page?

> I do get Typescript editor and validator, which complains that every single identifier is a duplicate, although Ctrl-Shift-G doesn't find a second instance.

Validation is done by tsserver, it should work. Please share your project, and tell me which file causes problem.

**Comment by Rhobal** [comment]
Thanks for the quick response!
I didn't find the preferences because I looked for it as a main topic like on the screenshots, not under JavaScript. I took the liberty to add the preferences path to your wiki.

I also found the reason for the Duplicate Identifiers, as "Build All.." copied all ts files to /target, so I moved tsconfig.jsob to /src

Here is a test project; it has tsconfig.json at /src and compiles with tsc but doesn't show the described TypeScript nature. I also don't get the "Add TypeSycript Build Path" menu entry and I don't get compile on save.
[ts-test.zip](https://github.com/angelozerr/typescript.java/files/501601/ts-test.zip)

**Comment by angelozerr** [comment]
>  I took the liberty to add the preferences path to your wiki. 

Thanks!

>  I also don't get the "Add TypeSycript Build Path" 

The demo is out of date. It's `TypeScript -> Add TypeSycript Build Path`

**Comment by Rhobal** [comment]
It seems I was in the wrong perspective; TypeScript Menus and Preferences are only shown in **JavaScript perspective**. Added this info to the Wiki.

I also lacked the "build automatically flag" in the project.
Right now, it looks great, thanks for the support!!
