### ISSUE TITLE
"Duplicate identifier" in maven project; validator should ignore ts files not on build path

### ISSUE THREAD

**Issue by Rhobal** [angelozerr/typescript.java#92]
I try to use typescript.java in a maven project, with `tsconfig.json` in the root folder
Maven copies everything to `/target` on build. Apparently, these copies are picked up by the TypeScript validator and generates "Duplicate identifier" errors for every identifier.

It can be remediated by moving `tsconfig.json` to `/src`. But why does the validator pick up files that are not on the tsconfig build path ("`rootDir`")? Shouldn't it ignore these files?

**Comment by angelozerr** [comment]
I have removed TypeScript validator for 1.1.0 because:

 * not very performant. TypeScritpt Validator
 * TypeScript builder plays the same goal.

So please try with 1.1.0-SNAPSHOT

**Comment by Rhobal** [comment]
I am using 1.1.0-SNAPSHOT. So maybe the error didn't come from the validator (guessed wrong, sorry) but from the builder. But the error _is_ there due to the copy in `/target`

**Comment by angelozerr** [comment]
Please share a simple project which causes your problem.

**Comment by Rhobal** [comment]
I tried to reproduce in a simple project, and noticed that the issue seems to be a "feature" of typescript: It complains that there are `.ts` files outside the source path and then compiles them anyway...

I will just keep my `tsconfig.json` in the `/src` folder
